"""Daftar fitur aplikasi beserta statusnya, disalin dari dokumen \"Daftar Fitur Rinci Aplikasi Belajar Bahasa Jepang\" (6 Oktober 2026).

Dipakai pembangun buku kasus uji untuk memeriksa bahwa setiap fitur yang tersedia (atau sebagian tersedia) punya minimal satu kasus uji,
dan untuk mengisi lembar \"Cakupan Fitur\". Bila dokumen fitur diperbarui, perbarui juga berkas ini.
"""

# (kode, nama fitur, status: Tersedia | Sebagian | Belum, kelompok)
FITUR = [
    ('AK-01', 'Pendaftaran lewat undangan', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-02', 'Tautan undangan bermasalah', 'Sebagian', 'Murid: Akun dan masuk'),
    ('AK-03', 'Pengenalan awal', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-04', 'Masuk', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-05', 'Penguncian akun', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-06', 'Lupa password', 'Sebagian', 'Murid: Akun dan masuk'),
    ('AK-07', 'Membuat password baru', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-08', 'Keluar', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-09', 'Penempatan kelas otomatis', 'Tersedia', 'Murid: Akun dan masuk'),
    ('AK-10', 'Email otomatis dari aplikasi', 'Belum', 'Murid: Akun dan masuk'),
    ('AK-11', 'Tes penempatan level', 'Belum', 'Murid: Akun dan masuk'),
    ('BR-01', 'Ringkasan di Beranda', 'Tersedia', 'Murid: Beranda dan jalur belajar'),
    ('BR-02', 'Lanjutkan belajar', 'Tersedia', 'Murid: Beranda dan jalur belajar'),
    ('BR-03', 'Peta jalur belajar', 'Tersedia', 'Murid: Beranda dan jalur belajar'),
    ('BR-04', 'Pelajaran terbuka berurutan', 'Tersedia', 'Murid: Beranda dan jalur belajar'),
    ('PL-01', 'Halaman pelajaran', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-02', 'Soal yang salah diulang', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-03', 'Soal pilih jawaban', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-04', 'Soal susun kalimat', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-05', 'Catatan tata bahasa', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-06', 'Mengulang pelajaran', 'Tersedia', 'Murid: Pelajaran dan soal'),
    ('PL-07', 'Pelajaran checkpoint', 'Sebagian', 'Murid: Pelajaran dan soal'),
    ('PL-08', 'Jenis soal lain', 'Belum', 'Murid: Pelajaran dan soal'),
    ('PL-09', 'Suara di halaman pelajaran', 'Belum', 'Murid: Pelajaran dan soal'),
    ('PL-10', 'Kuis harian dan ujian akhir unit', 'Belum', 'Murid: Pelajaran dan soal'),
    ('PL-11', 'Saran mengulang pelajaran terlemah', 'Belum', 'Murid: Pelajaran dan soal'),
    ('NL-01', 'Penilaian dan syarat lulus', 'Tersedia', 'Murid: Nilai, bintang, dan XP'),
    ('NL-02', 'Bintang', 'Tersedia', 'Murid: Nilai, bintang, dan XP'),
    ('NL-03', 'XP (poin belajar)', 'Tersedia', 'Murid: Nilai, bintang, dan XP'),
    ('NL-04', 'Halaman hasil', 'Tersedia', 'Murid: Nilai, bintang, dan XP'),
    ('NL-05', 'Level akun', 'Sebagian', 'Murid: Nilai, bintang, dan XP'),
    ('NL-06', 'Target XP harian', 'Sebagian', 'Murid: Nilai, bintang, dan XP'),
    ('MT-01', 'Unit Hiragana', 'Tersedia', 'Murid: Materi yang tersedia'),
    ('MT-02', 'Unit 3: Percakapan di Tempat Kerja', 'Sebagian', 'Murid: Materi yang tersedia'),
    ('MT-03', 'Skenario percakapan', 'Sebagian', 'Murid: Materi yang tersedia'),
    ('MT-04', 'Isi Kamus', 'Sebagian', 'Murid: Materi yang tersedia'),
    ('MT-05', 'Katakana, Dasar, dan N5', 'Belum', 'Murid: Materi yang tersedia'),
    ('MT-06', 'Suara pelafalan materi', 'Belum', 'Murid: Materi yang tersedia'),
    ('PC-01', 'Daftar skenario', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-02', 'Pengantar skenario', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-03', 'Mode Latihan', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-04', 'Mode Tes', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-05', 'Skor, kelulusan, dan XP', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-06', 'Halaman hasil percakapan', 'Tersedia', 'Murid: Percakapan: skenario latihan'),
    ('PC-07', 'Suara pada baris dialog', 'Belum', 'Murid: Percakapan: skenario latihan'),
    ('PC-08', 'Pilih peran, sembunyikan bacaan atau arti, tambah kosakata ke flashcard', 'Belum', 'Murid: Percakapan: skenario latihan'),
    ('AI-01', 'Pintu masuk', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-02', 'Pilih situasi', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-03', 'Pilih teman bicara', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-04', 'Berbicara lewat mikrofon', 'Sebagian', 'Murid: Ngobrol dengan AI'),
    ('AI-05', 'Memeriksa hasil rekaman', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-06', 'Mengetik', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-07', 'Kalimat pembuka', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-08', 'Balasan teman bicara', 'Sebagian', 'Murid: Ngobrol dengan AI'),
    ('AI-09', 'Koreksi kalimat', 'Sebagian', 'Murid: Ngobrol dengan AI'),
    ('AI-10', 'Mendengarkan balasan', 'Sebagian', 'Murid: Ngobrol dengan AI'),
    ('AI-11', 'Minta contoh jawaban', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-12', 'Jatah harian', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-13', 'Bila mikrofon tidak bisa dipakai', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-14', 'Bila layanan AI belum aktif atau bermasalah', 'Tersedia', 'Murid: Ngobrol dengan AI'),
    ('AI-15', 'Penilaian pengucapan', 'Belum', 'Murid: Ngobrol dengan AI'),
    ('AI-16', 'Kartu koreksi dan terjemahan balasan', 'Belum', 'Murid: Ngobrol dengan AI'),
    ('AI-17', 'Riwayat percakapan untuk pengajar', 'Belum', 'Murid: Ngobrol dengan AI'),
    ('KM-01', 'Pencarian kata', 'Tersedia', 'Murid: Kamus'),
    ('KM-02', 'Isi hasil pencarian', 'Tersedia', 'Murid: Kamus'),
    ('KM-03', 'Suara kata', 'Sebagian', 'Murid: Kamus'),
    ('FC-01', 'Kartu otomatis', 'Tersedia', 'Murid: Flashcard'),
    ('FC-02', 'Sesi flashcard', 'Tersedia', 'Murid: Flashcard'),
    ('FC-03', 'Jadwal pengulangan', 'Tersedia', 'Murid: Flashcard'),
    ('FC-04', 'Suara di kartu', 'Sebagian', 'Murid: Flashcard'),
    ('FC-05', 'Kartu dari seluruh kosakata dan mode tes', 'Belum', 'Murid: Flashcard'),
    ('GM-01', 'Streak', 'Tersedia', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-02', 'Leaderboard (peringkat mingguan)', 'Tersedia', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-03', 'Lencana (badge)', 'Sebagian', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-04', 'Profil', 'Tersedia', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-05', 'Ubah nama dan target XP harian', 'Tersedia', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-06', 'Foto profil, statistik belajar, dan daftar lencana', 'Belum', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('GM-07', 'Pembekuan streak, lencana peringkat, dan pengingat streak', 'Belum', 'Murid: Streak, Leaderboard, Lencana, dan Profil'),
    ('TP-01', 'Tema warna', 'Tersedia', 'Murid: Tampilan dan kenyamanan'),
    ('TP-02', 'Tampilan menyesuaikan layar', 'Tersedia', 'Murid: Tampilan dan kenyamanan'),
    ('TP-03', 'Animasi dan perayaan', 'Tersedia', 'Murid: Tampilan dan kenyamanan'),
    ('TP-04', 'Mudah dibaca dan dipakai', 'Tersedia', 'Murid: Tampilan dan kenyamanan'),
    ('TP-05', 'Bahasa Indonesia', 'Tersedia', 'Murid: Tampilan dan kenyamanan'),
    ('TP-06', 'Dibuka seperti aplikasi', 'Sebagian', 'Murid: Tampilan dan kenyamanan'),
    ('AD-01', 'Masuk admin', 'Tersedia', 'Admin: Akses dan akun admin'),
    ('AD-02', 'Peran admin', 'Sebagian', 'Admin: Akses dan akun admin'),
    ('AD-03', 'Menu admin', 'Tersedia', 'Admin: Akses dan akun admin'),
    ('AD-04', 'Akun murid uji', 'Tersedia', 'Admin: Akses dan akun admin'),
    ('DB-01', 'Angka ringkas', 'Tersedia', 'Admin: Dashboard'),
    ('DB-02', 'Sebaran streak', 'Tersedia', 'Admin: Dashboard'),
    ('DB-03', 'Penyelesaian per kelas', 'Tersedia', 'Admin: Dashboard'),
    ('UD-01', 'Undang satu murid', 'Sebagian', 'Admin: Undangan'),
    ('UD-02', 'Daftar undangan', 'Tersedia', 'Admin: Undangan'),
    ('UD-03', 'Kirim ulang undangan', 'Sebagian', 'Admin: Undangan'),
    ('UD-04', 'Cabut undangan', 'Tersedia', 'Admin: Undangan'),
    ('UD-05', 'Undangan banyak sekaligus lewat file CSV', 'Sebagian', 'Admin: Undangan'),
    ('KL-01', 'Buat kelas', 'Tersedia', 'Admin: Kelas'),
    ('KL-02', 'Daftar kelas', 'Tersedia', 'Admin: Kelas'),
    ('KL-03', 'Arsipkan dan buka arsip', 'Tersedia', 'Admin: Kelas'),
    ('KL-04', 'Detail dan ubah kelas', 'Sebagian', 'Admin: Kelas'),
    ('MR-01', 'Daftar murid', 'Tersedia', 'Admin: Murid'),
    ('MR-02', 'Data murid', 'Tersedia', 'Admin: Murid'),
    ('MR-03', 'Pindah kelas', 'Tersedia', 'Admin: Murid'),
    ('MR-04', 'Nonaktifkan dan aktifkan akun', 'Tersedia', 'Admin: Murid'),
    ('MR-05', 'Kirim email reset password', 'Sebagian', 'Admin: Murid'),
    ('MR-06', 'Perkembangan belajar', 'Tersedia', 'Admin: Murid'),
    ('MR-07', 'Grafik kalender aktivitas', 'Belum', 'Admin: Murid'),
    ('PG-01', 'Halaman Pengaturan', 'Belum', 'Admin: Pengaturan dan fitur lanjutan'),
    ('PG-02', 'Ekspor laporan, pengumuman, editor materi, dan verifikasi dua langkah', 'Belum', 'Admin: Pengaturan dan fitur lanjutan'),
    ('KN-01', 'Membuat unit dari dokumen Word', 'Tersedia', 'Admin: Pelajaran baru dari dokumen Word'),
    ('KN-02', 'Pemeriksaan salah ketik', 'Tersedia', 'Admin: Pelajaran baru dari dokumen Word'),
]
