"""Kasus uji: Pelajaran dan soal (PL), Nilai/bintang/XP/streak (NL), Percakapan skenario (PC)."""
from kasus_dasar import A_NL, A_PC, A_PL, K

KASUS = [
    # ---------------------------------------------------------------------------------------------- Pelajaran dan soal
    K("TC-PL-01", A_PL, "Murid", "P1", "Pelajaran terbuka dengan soal, bilah kemajuan 0, dan tombol tutup",
      "Sudah masuk; pelajaran pertama terbuka.",
      ["Dari Beranda tekan Lanjutkan Belajar (atau bulatan pelajaran)."],
      "Terbuka layar soal: bilah kemajuan di 0, tombol X (Tutup pelajaran), dan satu soal (pilih jawaban atau susun kalimat). Soal susun: tombol Periksa Jawaban mati sampai ada kepingan dipilih.",
      "PL-01, PL-03, PL-04"),
    K("TC-PL-02", A_PL, "Murid", "P1", "Menjawab satu soal: umpan balik tampil dan jawaban terkunci",
      "Pelajaran terbuka.",
      ["Jawab soal pertama (pilih satu jawaban, atau susun kepingan lalu Periksa Jawaban).", "Perhatikan panel yang muncul, lalu tekan Lanjut."],
      "Panel hijau \"Benar!\" bila benar; panel merah \"Kurang tepat\" dengan \"Jawaban yang benar: ...\" bila salah. Pilihan/kepingan tidak bisa diubah lagi. Lanjut membuka soal berikutnya; "
      "jawaban benar menaikkan bilah kemajuan, jawaban salah tidak.",
      "PL-02, PL-03, PL-04"),
    K("TC-PL-03", A_PL, "Murid", "P1", "Tombol Tutup (X) kembali ke Beranda tanpa menyimpan hasil",
      "Pelajaran terbuka, satu soal sudah dijawab.",
      ["Tekan X di pojok kiri atas.", "Bandingkan \"Pelajaran selesai\" sebelum dan sesudah."],
      "Murid kembali ke Beranda; tidak ada hasil, bintang, atau XP yang tercatat dan hitungan pelajaran selesai tidak berubah.",
      "PL-01"),
    K("TC-PL-04", A_PL, "Murid", "P2", "Memuat ulang di tengah pelajaran memulai lagi dari awal",
      "Pelajaran terbuka, beberapa soal sudah dijawab.",
      ["Tekan F5."],
      "Pelajaran dimuat ulang dari soal pertama dengan bilah kemajuan 0 (kemajuan di tengah pelajaran tidak disimpan). Tidak ada galat.",
      "PL-01", "Perilaku yang dirancang; catat bila produk ingin kemajuan tengah pelajaran disimpan."),
    K("TC-PL-05", A_PL, "Murid", "P1", "Soal yang salah diulang di akhir dan akurasi dihitung dari semua jawaban",
      "Pelajaran yang belum pernah dikerjakan (mis. l1 dengan 19 soal).",
      ["Jawab dengan sengaja salah pada 3 soal berbeda, sisanya benar.", "Perhatikan bahwa soal yang salah muncul lagi di akhir sampai dijawab benar.", "Selesaikan pelajaran dan baca Akurasi."],
      "Setiap soal salah muncul lagi di akhir. Total jawaban = jumlah soal + jumlah jawaban salah. Contoh pelajaran 19 soal dengan 3 salah: 19 benar dari 22 jawaban = Akurasi 86%.",
      "PL-02, NL-01"),
    K("TC-PL-06", A_PL, "Murid", "P1", "Layar hasil menjelaskan lulus atau belum lulus",
      "Pelajaran selesai dikerjakan.",
      ["Baca layar hasil (kerjakan sekali dengan banyak salah supaya \"Belum Lulus\", sekali dengan sedikit salah supaya \"Lulus!\")."],
      "Belum Lulus: pesan \"Jangan menyerah, coba sekali lagi ya!\", tanpa bintang dan tanpa XP. Lulus: perayaan, bintang, dan lencana XP bila pertama kali. Keduanya menampilkan Akurasi, Skor terbaik, "
      "Jumlah percobaan, tombol Coba Lagi dan Kembali ke Beranda.",
      "NL-04, PL-06"),
    K("TC-PL-07", A_PL, "Murid", "P2", "Coba Lagi mengulang pelajaran dari soal pertama",
      "Di layar hasil.",
      ["Tekan Coba Lagi."],
      "Pelajaran terbuka lagi dengan bilah kemajuan 0 dan soal dari awal.",
      "PL-06"),
    K("TC-PL-08", A_PL, "Murid", "P2", "Layar hasil dibuka langsung tanpa mengerjakan",
      "Sudah masuk.",
      ["Buka /learn/l1/result langsung di browser."],
      "Murid dikembalikan ke Beranda (layar hasil hanya bisa muncul setelah mengerjakan pelajaran).",
      "NL-04"),
    K("TC-PL-09", A_PL, "Murid", "P2", "Catatan tata bahasa pelajaran bisa dibuka dan ditutup",
      "Buka pelajaran pertama unit \"Percakapan di Tempat Kerja\" (/learn/k3_l1; boleh lewat alamat langsung walau terkunci).",
      ["Tekan tombol Catatan di bilah atas.", "Baca isinya, gulir bila panjang.", "Tekan Catatan lagi."],
      "Panel \"Catatan tata bahasa\" terbuka di bawah bilah atas dengan judul dan isi (pola, rangkaian bentuk, contoh), bisa digulir, dan tertutup saat tombol ditekan lagi.",
      "PL-05"),
    K("TC-PL-10", A_PL, "Murid", "P1", "Putaran tanpa salah: Lulus, akurasi 100%, 3 bintang, XP hanya sekali",
      "Pelajaran yang belum pernah lulus.",
      ["Kerjakan semua soal dengan benar (jika perlu, lihat jawaban dari putaran sebelumnya).", "Baca layar hasil."],
      "Judul \"Lulus!\", Akurasi 100%, tiga bintang menyala, lencana \"+30 XP\" (pelajaran biasa, pertama kali lulus), Skor terbaik 100%.",
      "NL-01, NL-02, NL-03, PL-01"),
    K("TC-PL-11", A_PL, "Murid", "P2", "Soal pilih jawaban tampil jelas dan memberi warna benar/salah",
      "Pelajaran dengan soal pilih (semua pelajaran).",
      ["Pilih jawaban yang benar pada satu soal dan jawaban yang salah pada soal lain."],
      "Huruf/kata soal tampil besar (kana di ubin berwarna), pilihan berupa empat tombol. Setelah memilih: jawaban benar hijau; pilihan salah merah dan bergetar singkat; sisanya redup. Teks \"Jawaban yang benar: ...\" muncul bila salah.",
      "PL-03, TP-04"),
    K("TC-PL-12", A_PL, "Murid", "P2", "Soal susun kalimat: ketuk kepingan, ketuk lagi untuk membatalkan, Ulangi",
      "Pelajaran yang punya soal susun (mis. pelajaran Unit 3).",
      ["Ketuk beberapa kepingan di bawah: pindah ke kotak jawaban.", "Ketuk satu kepingan di kotak jawaban: kembali ke bawah.", "Tekan Ulangi.", "Susun benar lalu tekan Periksa Jawaban."],
      "Kepingan berpindah sesuai ketukan, Ulangi mengosongkan kotak jawaban, Periksa Jawaban baru aktif bila ada kepingan, dan setelah diperiksa kepingan terkunci.",
      "PL-04"),
    K("TC-PL-13", A_PL, "Murid", "P2", "Urutan kepingan harus benar-benar sama",
      "Soal susun.",
      ["Susun semua kepingan yang benar tetapi tukar dua kepingan, lalu Periksa Jawaban."],
      "Dinilai \"Kurang tepat\" dan jawaban yang benar ditampilkan; soal diulang di akhir.",
      "PL-04"),
    K("TC-PL-14", A_PL, "Murid", "P2", "Gangguan jaringan saat mengirim hasil pelajaran",
      "Hampir selesai mengerjakan satu pelajaran.",
      ["Pada soal terakhir, nyalakan DevTools > Network > Offline.", "Tekan Lanjut."],
      "Muncul \"Gagal mengirim hasil belajar.\" dengan tombol Kembali ke Beranda; tidak ada layar kosong. Setelah jaringan kembali, mengerjakan ulang pelajaran berhasil.",
      "PL-01", "Catatan UX: jawaban yang sudah dikerjakan tidak bisa dikirim ulang dari layar galat; murid harus mengulang pelajaran."),
    K("TC-PL-15", A_PL, "Murid", "P3", "Klik ganda cepat tidak menghitung dua jawaban",
      "Soal pilih jawaban.",
      ["Klik dua kali cepat pada satu pilihan.", "Lihat bilah kemajuan dan panel umpan balik."],
      "Hanya satu jawaban terhitung; satu panel umpan balik; pilihan langsung terkunci.",
      "PL-03"),
    K("TC-PL-16", A_PL, "Murid", "P3", "Tombol kembali browser di tengah pelajaran",
      "Pelajaran terbuka, beberapa soal sudah dijawab.",
      ["Tekan tombol kembali browser.", "Tekan tombol maju browser."],
      "Kembali membuka Beranda tanpa hasil tersimpan; maju membuka pelajaran dari awal. Tidak ada layar kosong.",
      "PL-01"),
    K("TC-PL-17", A_PL, "Murid", "P3", "Dua tab menyelesaikan pelajaran yang sama",
      "Pelajaran yang belum pernah lulus.",
      ["Buka pelajaran di dua tab.", "Selesaikan keduanya sampai lulus."],
      "Jumlah percobaan bertambah dua, skor terbaik tetap yang tertinggi, XP pelajaran hanya diberikan satu kali.",
      "NL-03"),
    K("TC-PL-18", A_PL, "Murid", "P3", "Huruf Jepang tampil dengan gaya Jepang dan kana besar terbaca",
      "Komputer dan ponsel.",
      ["Buka pelajaran Hiragana dan pelajaran Unit 3.", "Perhatikan kanji (mis. 会議, 乗る) dan kana pada soal."],
      "Huruf Han tampil bergaya Jepang (bukan Tionghoa), tidak ada kotak kosong, dan kana pada ubin soal cukup besar.",
      "TP-04"),
    K("TC-PL-19", A_PL, "Murid", "P3", "Belum ada suara di pelajaran: tidak ada tombol audio yang rusak",
      "Server tanpa audio (suara pelajaran belum dibuat).",
      ["Buka beberapa pelajaran.", "Cari tombol atau ikon speaker."],
      "Tidak ada tombol suara yang tampil tetapi tidak berfungsi, dan tidak ada janji suara di layar. Bila audio sudah dibuat, tombolnya berbunyi.",
      "PL-09, MT-06"),
    K("TC-PL-20", A_PL, "Murid", "P2", "Pelajaran Unit 3 (kalimat panjang) tampil rapi di layar ponsel",
      "Ponsel atau emulasi lebar 360 px.",
      ["Buka /learn/k3_l1 dan /learn/k3_l4.", "Kerjakan beberapa soal susun dengan banyak kepingan."],
      "Kepingan membungkus ke baris berikutnya, tidak melebihi lebar layar, tidak ada gulir ke samping, dan teks Jepang tidak terpotong di tengah kata.",
      "PL-04, TP-02"),

    # ------------------------------------------------------------------------------------ Nilai, bintang, XP, streak
    K("TC-NL-01", A_NL, "Murid", "P1", "Beranda mencerminkan kemajuan setelah lulus",
      "Murid baru yang baru lulus pelajaran pertama.",
      ["Kembali ke Beranda lewat tombol di layar hasil.", "Periksa bulatan pelajaran, hitungan \"Pelajaran selesai\", dan pelajaran kedua."],
      "Pelajaran pertama berbintang emas (3 bintang bila 100%), \"Pelajaran selesai\" naik satu, pelajaran kedua terbuka, dan tombol Lanjutkan Belajar menunjuk pelajaran berikutnya.",
      "NL-02, BR-04"),
    K("TC-NL-02", A_NL, "Murid", "P1", "Streak mulai dihitung dan XP masuk ke peringkat mingguan",
      "Murid baru yang baru lulus pelajaran pertama.",
      ["Lihat kartu Streak di Beranda.", "Buka Leaderboard dan cari baris bertanda (kamu)."],
      "Streak minimal 1 hari. Baris murid di Leaderboard menampilkan XP yang sama dengan XP yang didapat (mis. 30 XP).",
      "GM-01, GM-02, NL-03"),
    K("TC-NL-03", A_NL, "Murid", "P1", "Mengulang pelajaran yang sudah lulus: tanpa XP baru, skor terbaik tidak turun",
      "Pelajaran yang sudah lulus 100%.",
      ["Kerjakan lagi dengan sengaja banyak salah sampai Belum Lulus.", "Kerjakan lagi tanpa salah."],
      "Tidak ada lencana XP pada pengulangan; \"Skor terbaik\" tetap 100%; \"Jumlah percobaan\" bertambah satu tiap hasil dikirim; Beranda tetap menampilkan 3 bintang.",
      "NL-03, PL-06"),
    K("TC-NL-04", A_NL, "Murid", "P1", "Ambang lulus dan bintang menurut akurasi",
      "Pelajaran yang belum pernah dikerjakan dan akun baru untuk tiap baris tabel (XP hanya diberikan pada kelulusan pertama).",
      ["Untuk pelajaran 19 soal (mis. l1), buat jumlah salah sengaja sesuai tabel di lembar Data Uji (0, 1, 2, 3, 4, 5 salah).", "Catat Akurasi, bintang, dan XP di layar hasil untuk tiap kasus."],
      "0 salah: 100%, 3 bintang, +30 XP. 1 salah: 95%, 2 bintang, +20. 2 salah: 90%, 2 bintang, +20. 3 salah: 86%, 1 bintang, +10. 4 salah: 83%, 1 bintang, +10. 5 salah: 79%, Belum Lulus, tanpa XP.",
      "NL-01, NL-02, NL-03", "Akurasi = benar / semua jawaban (termasuk pengulangan) dibulatkan. Lulus bila akurasi 80% atau lebih. Boleh dikerjakan pada pelajaran yang berbeda dengan menghitung ulang di lembar Data Uji."),
    K("TC-NL-05", A_NL, "Murid", "P2", "Streak bertambah tiap hari belajar dan kembali ke 1 setelah satu hari terlewat",
      "Murid uji, beberapa hari berturut-turut (atau ubah tanggal data uji di database).",
      ["Hari 1: lulus satu pelajaran; catat Streak.", "Hari 2: lulus satu pelajaran; catat Streak.", "Lewati satu hari penuh tanpa belajar; hari 4: belajar lagi."],
      "Hari 1: 1. Hari 2: 2. Hari 4: kembali 1, sedangkan \"Terpanjang\" tetap 2. Belajar lebih dari sekali dalam sehari tidak menambah streak.",
      "GM-01", "Uji lintas hari. Pergantian hari mengikuti zona waktu server (bawaan produksi Asia/Jakarta). Untuk mempercepat: UPDATE streaks SET last_activity_date = current_date - 1, \"current\" = 2 WHERE user_id = (SELECT id FROM users WHERE email = '<email uji>'); lalu belajar hari ini dan lihat hasilnya."),
    K("TC-NL-06", A_NL, "Murid", "P3", "Target XP harian dan level belum punya penunjuk di layar",
      "Sudah masuk.",
      ["Periksa Beranda dan Profil mencari penunjuk kemajuan menuju target harian dan penunjuk level."],
      "Target harian hanya tampil sebagai angka di Profil dan sambutan (\"N XP/hari\"). Belum ada penunjuk kemajuan harian maupun level (sesuai dokumen fitur NL-05 dan NL-06 berstatus Sebagian). Pastikan tidak ada teks yang menjanjikan fitur ini.",
      "NL-05, NL-06"),

    # ------------------------------------------------------------------------------------------ Percakapan (skenario)
    K("TC-PC-01", A_PC, "Murid", "P1", "Halaman Percakapan: kartu Ngobrol dengan AI dan daftar skenario latihan",
      "Sudah masuk.",
      ["Buka Percakapan dari menu."],
      "Kartu \"Ngobrol dengan AI\" (bertanda Baru) di atas, lalu bagian \"Skenario latihan\" berisi kartu 自己紹介 / Perkenalan Diri lengkap dengan level (N5), peran, dan perkiraan menit.",
      "PC-01"),
    K("TC-PC-02", A_PC, "Murid", "P1", "Layar pengantar menjelaskan dua mode",
      "Sudah masuk.",
      ["Buka skenario Perkenalan Diri."],
      "Judul Jepang dan Indonesia, chip peran/menit/level, kotak Catatan Tata Bahasa, kartu Latihan (\"boleh mengulang tanpa batas\") dan kartu Tes (\"hanya 3 kali salah, lalu sesi berhenti\") dengan tombol masing-masing.",
      "PC-02"),
    K("TC-PC-03", A_PC, "Murid", "P1", "Jawaban salah di Latihan: koreksi muncul dan baris yang sama diulang",
      "Skenario terbuka, mode Latihan.",
      ["Lewati narasi dengan Lanjut.", "Pada baris pilihan, pilih jawaban yang salah.", "Baca panel dan tekan Coba Lagi."],
      "Panel merah \"Kurang tepat\" memuat catatan koreksi dalam bahasa Indonesia, tombol bertuliskan Coba Lagi, pilihan terkunci. Setelah ditekan, baris yang sama muncul lagi dengan pilihan aktif dan kemajuan tidak bergeser.",
      "PC-03"),
    K("TC-PC-04", A_PC, "Murid", "P1", "Latihan dimainkan sampai selesai: hasil tampil dan tidak memberi XP",
      "Skenario terbuka.",
      ["Pilih Latihan dan selesaikan semua baris dengan jawaban benar.", "Baca layar hasil."],
      "Hasil: Lulus!, Akurasi 100%, Skor 100, Jawaban salah 0, tanpa lencana XP. Tombol Coba Lagi dan Daftar Skenario ada.",
      "PC-03, PC-05, PC-06"),
    K("TC-PC-05", A_PC, "Murid", "P2", "Di Latihan boleh salah berkali-kali; hasil Belum Lulus bila akurasi di bawah 80%",
      "Skenario terbuka, mode Latihan.",
      ["Pada baris pertama pilih jawaban salah 5 kali berturut-turut (Coba Lagi tiap kali).", "Selesaikan sisanya dengan benar."],
      "Sesi tidak pernah berhenti karena salah. Hasil \"Belum Lulus\" dengan akurasi di bawah 80% dan jumlah \"Jawaban salah\" 5, tanpa XP.",
      "PC-03, PC-05"),
    K("TC-PC-06", A_PC, "Murid", "P1", "Di Tes, kesalahan keempat menghentikan sesi",
      "Skenario terbuka, mode Mulai Tes.",
      ["Pada baris pilihan pilih jawaban salah empat kali berturut-turut."],
      "Pada kesalahan keempat tombol bertuliskan Lihat Hasil dan hasilnya \"Kesempatan Habis\" dengan pesan \"Terlalu banyak jawaban salah -- sesi tes berhenti di tengah jalan.\" dan Jawaban salah 4.",
      "PC-04, PC-06"),
    K("TC-PC-07", A_PC, "Murid", "P1", "Di Tes tanpa salah: Lulus, akurasi 100%, skor 100",
      "Skenario terbuka, mode Mulai Tes.",
      ["Jawab semua baris pilihan dengan benar, dalam waktu kurang dari perkiraan menit skenario."],
      "Hasil: Lulus!, Akurasi 100%, Skor 100 (akurasi ditambah bonus waktu, maksimal 100).",
      "PC-04, PC-05"),
    K("TC-PC-08", A_PC, "Murid", "P1", "XP dari Tes hanya sekali per skenario dan sama dengan perubahan di peringkat",
      "Murid yang belum pernah Tes skenario ini; catat XP di Leaderboard sebelum mulai.",
      ["Selesaikan satu Tes (lulus atau gagal).", "Ulangi Tes sampai lulus.", "Cek lencana XP di tiap layar hasil dan XP di Leaderboard."],
      "Total XP Tes untuk skenario ini maksimal 20 dan hanya diberikan sekali. Selisih XP di Leaderboard sama dengan jumlah lencana XP di layar hasil. Latihan tidak pernah memberi XP.",
      "PC-05", "Temuan diketahui: XP 20 diberikan pada percobaan Tes PERTAMA walau percobaan itu gagal (Kesempatan Habis); kelulusan sesudahnya tidak memberi XP lagi. Catatan docs/PLAN.md menulis \"percobaan TEST pertama yang LULUS\". Perlu keputusan pemilik produk (lihat lembar Temuan Awal)."),
    K("TC-PC-09", A_PC, "Murid", "P2", "Alamat skenario yang tidak dikenal",
      "Sudah masuk.",
      ["Buka /conversation/tidak-ada."],
      "Pesan \"Gagal memuat skenario.\" dan tombol Kembali ke Percakapan.",
      "PC-01"),
    K("TC-PC-10", A_PC, "Murid", "P2", "Layar hasil percakapan dibuka langsung",
      "Sudah masuk.",
      ["Buka /conversation/perkenalan/result langsung."],
      "Murid dialihkan ke daftar Percakapan.",
      "PC-06"),
    K("TC-PC-11", A_PC, "Murid", "P2", "Tombol Tutup (X) di tengah percakapan",
      "Skenario terbuka dan sudah dimulai.",
      ["Tekan X di pojok kiri atas."],
      "Murid kembali ke daftar Percakapan tanpa hasil tersimpan.",
      "PC-02"),
    K("TC-PC-12", A_PC, "Murid", "P2", "Baris narasi menampilkan teks Jepang, romaji, dan arti",
      "Skenario terbuka.",
      ["Mulai Latihan dan baca tiap baris narasi (teman bicara)."],
      "Setiap baris narasi menampilkan nama pembicara, kalimat Jepang besar, romaji, dan arti Indonesia; tombol Lanjut (Selesai di baris terakhir).",
      "PC-03"),
    K("TC-PC-13", A_PC, "Murid", "P3", "Urutan opsi jawaban tidak diacak",
      "Skenario terbuka.",
      ["Mulai skenario dua kali dan bandingkan urutan opsi pada baris pilihan yang sama."],
      "Urutan opsi pada baris yang sama selalu sama (opsi percakapan tidak diacak, berbeda dari soal pelajaran).",
      "PC-03", "Perilaku yang dirancang."),
    K("TC-PC-14", A_PC, "Murid", "P2", "Bonus waktu pada skor Tes",
      "Skenario dengan perkiraan 3 menit; Tes yang belum pernah dimainkan atau boleh diulang.",
      ["Mainkan Tes dengan SATU jawaban salah dan selesaikan dalam kurang dari 3 menit: catat Skor.",
       "Ulangi dengan satu salah tetapi sengaja diselesaikan antara 3 dan 4,5 menit: catat Skor.",
       "Ulangi dengan satu salah dan diselesaikan lebih dari 4,5 menit: catat Skor."],
      "Rumus: skor = akurasi + bonus waktu (selesai dalam perkiraan menit +10; sampai 1,5 kali perkiraan +5; lebih lambat +0), maksimal 100. Dengan satu salah di skenario ini akurasinya 67%, "
      "jadi skor 77 (cepat), 72 (agak lambat), 67 (lambat). Tanpa salah, skor tetap 100 karena dibatasi.",
      "PC-05"),
    K("TC-PC-15", A_PC, "Murid", "P3", "Belum ada suara pada baris dialog",
      "Server tanpa audio.",
      ["Buka skenario dan periksa baris dialog."],
      "Tidak ada tombol suara yang tampil rusak; tidak ada janji suara di layar.",
      "PC-07"),
]
