"""Kasus uji: API dan server (TC-API), Konten pelajaran (TC-KT), Keamanan, kinerja, pemulihan (TC-NF)."""
from kasus_dasar import A_API, A_KT, A_NF, K

SKRIP = "Jalankan: npm run test:api"
SKRIP_LENGKAP = "Jalankan: npm run test:api:lengkap"

KASUS = [
    # ------------------------------------------------------------------------------------------ API dan server (skrip)
    K("TC-API-01", A_API, "API", "P1", "Health API menjawab 200 dengan status ok", "Alamat API di qa/.env.", [SKRIP], "GET /health menjawab 200 dan {\"status\":\"ok\"}.", "TP-06"),
    K("TC-API-02", A_API, "Murid", "P1", "Aplikasi murid terbuka (HTML dengan elemen root)", "Alamat aplikasi murid di qa/.env.", [SKRIP], "Halaman utama menjawab 200 dan memuat elemen root aplikasi (bukan halaman galat server).", "TP-02"),
    K("TC-API-03", A_API, "Admin", "P1", "Aplikasi admin terbuka (HTML dengan elemen root)", "Alamat aplikasi admin di qa/.env.", [SKRIP], "Halaman utama menjawab 200 dan memuat elemen root aplikasi.", "AD-03"),
    K("TC-API-04", A_API, "API", "P1", "Header keamanan dasar API terpasang", "Alamat API.", [SKRIP], "X-Content-Type-Options: nosniff ada, X-Powered-By tidak ada, header batas laju (X-RateLimit-Limit) ada.", "AD-01"),
    K("TC-API-05", A_API, "API", "P2", "Jam server tidak melenceng lebih dari 5 menit", "Alamat API.", [SKRIP], "Selisih jam server dan komputer penguji kurang dari 5 menit (jam yang melenceng membuat token login dianggap kedaluwarsa).", "AK-04"),
    K("TC-API-06", A_API, "API", "P1", "Login murid memberi access token dan refresh token", "Akun murid uji.", [SKRIP], "POST /auth/login menjawab 200/201 dengan accessToken dan refreshToken.", "AK-04"),
    K("TC-API-07", A_API, "API", "P1", "Login salah ditolak 401 dengan pesan sama untuk email tak dikenal", "Tidak perlu akun.", [SKRIP], "Status 401 dengan pesan yang menyebut email atau password salah.", "AK-04"),
    K("TC-API-08", A_API, "API", "P1", "Rute murid tanpa token ditolak 401", "Tidak perlu akun.", [SKRIP], "/me, /path, /lessons/{id}, /scenarios, /dictionary, /flashcards/due, /leaderboard, /tutor/quota semuanya 401 tanpa token.", "AK-04"),
    K("TC-API-09", A_API, "API", "P1", "GET /me mengembalikan akun murid uji", "Login murid berhasil.", [SKRIP], "Email sama dengan akun uji, status ACTIVE, field nama/kelas/target XP lengkap.", "GM-04"),
    K("TC-API-10", A_API, "API", "P1", "GET /path berisi level, unit, dan pelajaran uji", "Login murid berhasil.", [SKRIP], "Ada minimal satu level, pelajaran uji (QA_LESSON_ID) ada, dan streak ada.", "BR-03"),
    K("TC-API-11", A_API, "API", "P1", "GET /lessons/{id} berisi unit dan soal", "Login murid berhasil.", [SKRIP], "Jawaban memuat unit dan lesson beserta soalnya.", "PL-01"),
    K("TC-API-12", A_API, "API", "P1", "Daftar skenario percakapan dan detailnya", "Login murid berhasil.", [SKRIP], "Minimal satu skenario terbit; detailnya memuat baris dialog.", "PC-01"),
    K("TC-API-13", A_API, "API", "P2", "Kamus mencari kata dan menolak pencarian kosong", "Login murid berhasil.", [SKRIP], "q=a menemukan kata dengan field lengkap; q kosong dijawab 400.", "KM-01"),
    K("TC-API-14", A_API, "API", "P2", "Kartu flashcard jatuh tempo dapat dibaca", "Login murid berhasil.", [SKRIP], "Jawaban berupa daftar (boleh kosong).", "FC-01"),
    K("TC-API-15", A_API, "API", "P2", "Leaderboard mingguan dapat dibaca dan dimulai hari Senin", "Login murid berhasil.", [SKRIP], "weekOf adalah hari Senin dan urutan XP menurun.", "GM-02"),
    K("TC-API-16", A_API, "API", "P2", "Katalog dan jatah Ngobrol dengan AI dapat dibaca", "Login murid berhasil.", [SKRIP], "Ada situasi dan karakter; jatah: used + remaining = limit.", "AI-12"),
    K("TC-API-17", A_API, "API", "P1", "Login admin memberi token dan /admin/auth/me benar", "Akun admin uji.", [SKRIP], "Token diberikan dan /admin/auth/me mengembalikan email admin.", "AD-01"),
    K("TC-API-18", A_API, "API", "P1", "Endpoint admin: dashboard, kelas, murid, undangan", "Login admin berhasil.", [SKRIP], "Keempatnya menjawab 200; dashboard memuat semua field ringkasan.", "DB-01, KL-02, MR-01, UD-02"),
    K("TC-API-19", A_API, "API", "P1", "Pemisahan hak akses murid dan admin", "Login murid dan admin berhasil.", [SKRIP], "Token murid ditolak di rute admin, token admin ditolak di rute murid, dan rute admin tanpa token 401.", "AD-01"),
    K("TC-API-20", A_API, "API", "P2", "Waktu respons tiap permintaan di bawah ambang", "Semua pemeriksaan sebelumnya sudah berjalan.", [SKRIP], "Tidak ada permintaan yang lebih lambat dari QA_LATENCY_MS (bawaan 1500 ms); ringkasan median/p95 dicetak.", "TP-04"),
    K("TC-API-21", A_API, "API", "P1", "PATCH /me menolak target XP tidak sah dan menyimpan yang sah", "Login murid berhasil.", [SKRIP_LENGKAP], "Target 25 dan nama spasi dijawab 400; target 10/50 tersimpan dan dikembalikan ke nilai semula.", "GM-05"),
    K("TC-API-22", A_API, "API", "P1", "Pengiriman hasil pelajaran: payload kosong 400, pelajaran terkunci 403", "Login murid berhasil.", [SKRIP_LENGKAP], "Hasil tanpa jawaban ditolak (400/403) bukan 200/500; hasil pelajaran terkunci ditolak 403.", "PL-01, BR-04"),
    K("TC-API-23", A_API, "API", "P2", "Validasi input login: format salah, badan kosong, JSON rusak", "Tidak perlu akun.", [SKRIP_LENGKAP], "Ketiganya dijawab 400 (tidak ada 500).", "AK-04"),
    K("TC-API-24", A_API, "API", "P1", "Lupa password: jawaban sama untuk email terdaftar dan tidak", "Murid uji kedua.", [SKRIP_LENGKAP], "Status dan isi jawaban identik sehingga tidak membocorkan siapa yang terdaftar.", "AK-06"),
    K("TC-API-25", A_API, "API", "P1", "Refresh token berputar dan pemakaian ulang token lama ditolak", "Murid uji kedua (QA_STUDENT2).", [SKRIP_LENGKAP], "Refresh memberi token baru; token lama dipakai ulang 401; token turunannya ikut dicabut (401).", "AK-04"),
    K("TC-API-26", A_API, "API", "P2", "Ngobrol dengan AI: permintaan tidak sah ditolak tanpa memakai jatah", "Login murid berhasil.", [SKRIP_LENGKAP], "Situasi tak dikenal, riwayat berakhir giliran AI, pesan 501 karakter, dan unggahan bukan audio ditolak 400/415; jatah tidak berkurang.", "AI-12, AI-06"),

    # ------------------------------------------------------------------------------------------------ Konten pelajaran
    K("TC-KT-01", A_KT, "Murid", "P1", "Hiragana: kana, romaji, dan urutan pengenalan huruf benar",
      "Jalankan npm run konten untuk membuat berkas pemeriksaan (reports/konten). Pemeriksa paham kana.",
      ["Buka reports/konten/kosakata.csv di Excel, saring Unit = unit_hiragana.", "Periksa tiap baris: kana dan romaji sesuai tabel hiragana baku.", "Isi kolom \"Hasil periksa\" dan \"Komentar\"."],
      "104 kana benar. Konvensi khusus (mis. ぢ = dji, づ = dzu) konsisten dan disepakati. Catat setiap salah ketik dengan ID barisnya.",
      "MT-01"),
    K("TC-KT-02", A_KT, "Murid", "P1", "Unit 3 (Percakapan di Tempat Kerja): kosakata dan kalimat benar secara bahasa",
      "Berkas reports/konten (kosakata.csv, kalimat.csv). Pemeriksa: pengajar bahasa Jepang.",
      ["Periksa 62 kosakata dan 145 kalimat: tulisan, kana, romaji, arti Indonesia.", "Periksa khusus 6 kalimat yang sudah diduga keliru (lihat dokumen fitur bagian 7) dan dua temuan romaji otomatis (paswādo, raigetu).", "Isi kolom Hasil periksa dan Komentar."],
      "Semua kalimat wajar secara bahasa dan artinya tepat. Salah ketik dan kalimat janggal dicatat untuk diperbaiki di konten sumber.",
      "MT-02", "Temuan awal: dua romaji diduga salah ketik, yaitu \"paswādo\" (seharusnya pasuwādo) di k3s_2_4_2 dan \"raigetu\" (seharusnya raigetsu) di k3s_5_5_2."),
    K("TC-KT-03", A_KT, "Murid", "P1", "Catatan tata bahasa Unit 3 (11 catatan) benar dan mudah dipahami",
      "reports/konten/catatan-tata-bahasa.csv atau layar Catatan di tiap pelajaran.",
      ["Baca tiap catatan: pola, rangkaian bentuk, contoh.", "Cocokkan dengan buku acuan pengajar."],
      "Penjelasan benar, urut, dan bahasa Indonesianya jelas bagi pemula.",
      "MT-02, PL-05"),
    K("TC-KT-04", A_KT, "Murid", "P2", "Skenario Perkenalan Diri: dialog, kunci jawaban, dan catatan koreksi",
      "reports/konten/skenario.csv.",
      ["Periksa tiap baris narasi (tulisan, romaji, arti).", "Periksa pilihan: hanya satu yang benar per baris dan yang salah punya catatan koreksi yang masuk akal."],
      "Dialog natural, jawaban benar memang tepat, catatan koreksi membantu murid memahami kesalahannya.",
      "MT-03, PC-03"),
    K("TC-KT-05", A_KT, "Murid", "P2", "Kunci soal susun: tidak ada susunan sah yang ditolak",
      "Pelajaran Unit 3 yang banyak memuat soal susun.",
      ["Kerjakan soal susun dan catat soal yang punya lebih dari satu susunan kalimat yang benar secara bahasa (mis. keterangan waktu bisa di depan atau belakang).", "Coba susunan alternatif itu."],
      "Susunan alternatif yang sah diterima, atau dicatat sebagai bug konten bila ditolak.",
      "PL-04, MT-02"),
    K("TC-KT-06", A_KT, "Murid", "P2", "Urutan bertahap: kana yang diuji sudah diperkenalkan",
      "Pelajaran Hiragana 1 sampai 7.",
      ["Untuk tiap pelajaran catat kana yang diajarkan (judul pelajaran).", "Periksa soal dan pilihan: apakah memuat kana yang belum diajarkan?"],
      "Soal hanya menguji kana yang sudah/sedang diajarkan; pilihan pengecoh boleh berupa kana lain, tetapi jawaban benar selalu dari kana yang sudah diajarkan.",
      "MT-01"),
    K("TC-KT-07", A_KT, "Murid", "P2", "Audio: berkas ada, bisa diputar, dan sesuai teks (setelah suara dibuat)",
      "Suara sudah dibuat di server (perintah tts:seed) dan layanan suara aktif.",
      ["Jalankan npm run konten -- --audio.", "Dengarkan sedikitnya 20 sampel acak dari kosakata dan kalimat (di pelajaran, Kamus, Flashcard)."],
      "Pemeriksaan otomatis tidak melaporkan audio rusak/tidak ada; di telinga, ucapan sesuai teks, kecepatan wajar, dan tidak terpotong.",
      "MT-06, KM-03, FC-04", "Saat kit ini dibuat server uji belum punya audio (367 dari 367 butir), jadi pemeriksaan ini baru bisa dijalankan setelah suara dibuat."),
    K("TC-KT-08", A_KT, "Murid", "P3", "Ejaan dan istilah bahasa Indonesia di seluruh layar",
      "Semua halaman murid dan admin.",
      ["Baca semua teks layar, pesan galat, dan petunjuk."],
      "Ejaan baku, istilah konsisten (mis. \"Masuk\", \"Keluar\", \"XP\"), tidak ada kalimat Inggris atau teks sisa pengembang.",
      "TP-05"),
    K("TC-KT-09", A_KT, "Murid", "P3", "Arti kata konsisten antara pelajaran, Kamus, dan Flashcard",
      "Kata yang muncul di beberapa tempat.",
      ["Pilih 10 kata; bandingkan arti di soal pelajaran, Kamus, dan Flashcard."],
      "Arti Indonesia sama di semua tempat.",
      "KM-02, FC-02"),
    K("TC-KT-10", A_KT, "Murid", "P3", "Konten pantas dan sesuai tingkat (N5/N4)",
      "Seluruh materi.",
      ["Baca kalimat dan skenario yang ada."],
      "Tidak ada konten yang menyinggung; tingkat kesulitan wajar untuk level yang tertulis.",
      "MT-01, MT-02, MT-03"),

    # ------------------------------------------------------------------------ Keamanan, kinerja, dan pemulihan
    K("TC-NF-01", A_NF, "Semua", "P1", "HTTPS aktif dan HTTP dialihkan ke HTTPS",
      "Server produksi/uji dengan domain.",
      ["curl -I http://<domain>.", "Buka https://<domain> di browser dan periksa gembok sertifikat."],
      "HTTP dialihkan ke HTTPS (301/308); sertifikat sah, tidak kedaluwarsa, dan cocok dengan domain; tidak ada peringatan browser atau konten campuran.",
      "TP-06", "Rekam suara hanya berfungsi lewat HTTPS."),
    K("TC-NF-02", A_NF, "Semua", "P1", "Header keamanan situs web",
      "Server produksi/uji.",
      ["curl -I https://<domain-murid>/ dan curl -I https://<domain-admin>/."],
      "X-Content-Type-Options: nosniff, X-Frame-Options: DENY, dan Referrer-Policy ada; header Server disembunyikan.",
      "AD-01", "Rekomendasi (dari membaca konfigurasi, belum dibuktikan di server sungguhan): tambahkan juga Strict-Transport-Security dan Content-Security-Policy di Caddyfile situs web, karena token masuk disimpan di penyimpanan browser."),
    K("TC-NF-03", A_NF, "Semua", "P1", "Dokumentasi API (Swagger) tidak terbuka ke publik",
      "Server produksi.",
      ["Buka https://<domain>/api/api-docs dan /api/api-docs-json."],
      "Keduanya menjawab 404 (\"Not found\").",
      "AD-01"),
    K("TC-NF-04", A_NF, "API", "P1", "CORS: asal yang tidak dikenal tidak diizinkan",
      "Akses terminal.",
      ["curl -i -H \"Origin: https://jahat.example\" <API>/health.", "curl -i -H \"Origin: <alamat murid resmi>\" <API>/health."],
      "Untuk origin asing tidak ada header Access-Control-Allow-Origin; untuk origin resmi header itu berisi origin resmi.",
      "AD-01"),
    K("TC-NF-05", A_NF, "API", "P1", "Pembatas permintaan (100 per menit per alamat IP)",
      "Akses terminal; jangan dari jaringan bersama yang sedang dipakai penguji lain.",
      ["for i in $(seq 1 120); do curl -s -o /dev/null -w \"%{http_code}\\n\" <API>/health; done | sort | uniq -c.", "Tunggu semenit lalu coba lagi."],
      "Sekitar 100 permintaan pertama 200, sisanya 429; setelah menunggu kembali 200.",
      "AD-01", "Karena batas dihitung per alamat IP, banyak penguji di satu jaringan kantor berbagi batas ini; atur jadwal uji otomatis agar tidak berbarengan."),
    K("TC-NF-06", A_NF, "API", "P1", "Murid tidak bisa mengubah field terlarang lewat PATCH /me",
      "Token murid uji.",
      ["curl -X PATCH <API>/me -H \"authorization: Bearer <token>\" -H \"content-type: application/json\" -d '{\"status\":\"INACTIVE\",\"classId\":\"x\",\"email\":\"a@b.c\"}'.", "GET /me dan bandingkan."],
      "Dijawab 400 (\"property status should not exist\" dst.) dan data tidak berubah.",
      "GM-05"),
    K("TC-NF-07", A_NF, "API", "P1", "Data pribadi tidak bocor",
      "Token murid dan token admin uji.",
      ["Periksa jawaban /me, /leaderboard, /dictionary, dan /admin/students.", "Periksa log API setelah login dan reset password."],
      "Tidak ada passwordHash, hash token, atau email murid lain di respons murid; leaderboard hanya memuat userId, nama, XP, peringkat; password tidak pernah tercetak di log.",
      "GM-02"),
    K("TC-NF-08", A_NF, "API", "P1", "Murid tidak bisa memakai rute admin atau mengakses murid lain",
      "Token murid uji dan ID murid lain.",
      ["GET /admin/students/<id murid lain> dengan token murid.", "Coba mengubah data murid lain lewat rute murid (tidak ada rute yang menerima ID murid lain)."],
      "Rute admin menolak token murid (401/403); tidak ada rute murid yang menerima ID pengguna lain.",
      "AD-01"),
    K("TC-NF-09", A_NF, "Semua", "P2", "Karakter berbahaya di semua kolom teks",
      "Admin dan murid uji.",
      ["Isi nama kelas, nama undangan, nama profil, dan kotak cari Kamus dengan: ' OR 1=1 --, <script>alert(1)</script>, <img src=x onerror=alert(1)>, ${7*7}, {{7*7}}.", "Buka semua halaman yang menampilkan teks itu."],
      "Teks tersimpan atau ditolak dengan pesan wajar; tidak ada galat 500, tidak ada skrip berjalan, tidak ada \"49\" (templat dievaluasi), tampilan tidak rusak.",
      "KM-01, GM-05, KL-01"),
    K("TC-NF-10", A_NF, "Murid", "P2", "Kecepatan muat Beranda di jaringan seluler",
      "Chrome DevTools > Lighthouse (mode seluler) atau Network > Fast 4G.",
      ["Muat Beranda dengan cache kosong.", "Jalankan Lighthouse dan catat Performance, FCP, LCP."],
      "Halaman tampil berguna dalam 3 detik pada Fast 4G, skor Performance 70 atau lebih di ponsel, dan ukuran unduhan awal wajar (di bawah sekitar 1 MB terkompresi).",
      "TP-04", "Catat angka aktual sebagai tolok ukur untuk rilis berikutnya."),
    K("TC-NF-11", A_NF, "API", "P2", "Beban ringan: 20 murid bersamaan",
      "Alat beban (k6, Artillery, atau 20 jendela browser) dan 20 akun uji.",
      ["Jalankan 20 murid yang masuk, membuka Beranda, mengerjakan satu pelajaran, dan mencari di Kamus selama 5 menit."],
      "Tidak ada galat 5xx, p95 waktu respons di bawah 1,5 detik, penggunaan CPU/memori server wajar, dan tidak ada murid yang tersangkut.",
      "TP-04", "Perhatikan batas 100 permintaan/menit per IP: beban dari satu IP akan terkena 429; uji dari beberapa IP atau naikkan batas di lingkungan uji."),
    K("TC-NF-12", A_NF, "Semua", "P2", "API dimulai ulang saat murid sedang belajar",
      "Akses ke server; murid sedang di tengah pelajaran.",
      ["Mulai ulang layanan API (docker compose restart api).", "Murid melanjutkan pelajaran sampai kirim hasil, lalu memuat ulang."],
      "Selama API mati muncul pesan galat yang jelas (bukan layar kosong); setelah hidup lagi aplikasi normal dan murid tidak diminta masuk ulang.",
      "AK-04"),
    K("TC-NF-13", A_NF, "Semua", "P2", "Redis mati: pesan jelas dan pulih sendiri",
      "Akses ke server lingkungan uji.",
      ["Hentikan Redis (docker compose stop redis).", "Coba masuk, buka Leaderboard, dan buka Ngobrol dengan AI.", "Nyalakan Redis lagi dan ulangi."],
      "Fitur yang butuh Redis (penguncian login, peringkat, jatah AI) menampilkan pesan galat yang jelas, tanpa teks teknis di layar; setelah Redis hidup semuanya normal.",
      "AK-05, GM-02, AI-12", "Perilaku ini belum terdokumentasi; catat apa yang sebenarnya terjadi untuk dijadikan keputusan produk."),
    K("TC-NF-14", A_NF, "Semua", "P2", "Cadangan dan pemulihan database",
      "Lingkungan uji dengan data; panduan di docs/DEPLOY.md.",
      ["Jalankan skrip cadangan (deploy/backup.sh atau pg-dump.sh).", "Pulihkan ke database kosong (pg-restore.sh).", "Masuk sebagai murid dan admin, periksa data."],
      "Pemulihan selesai tanpa galat; murid dan admin bisa masuk; XP, kemajuan pelajaran, kelas, dan undangan sama seperti sebelum dicadangkan.",
      "AD-04"),
    K("TC-NF-15", A_NF, "Murid", "P3", "Zona waktu pengguna dan batas hari",
      "Server dengan TZ Asia/Jakarta.",
      ["Belajar sekitar pukul 23:50 dan 00:10 WIB, catat Streak dan jatah AI.", "Ubah zona waktu perangkat penguji ke WITA/WIT dan UTC, ulangi."],
      "Pergantian hari streak, awal minggu Leaderboard, dan pengembalian jatah AI mengikuti zona waktu SERVER (bukan perangkat). Catat bila murid di zona waktu lain bingung.",
      "GM-01, GM-02, AI-12"),
]
