"""Kasus uji: Akun dan masuk (AK), Beranda dan jalur belajar (BR)."""
from kasus_dasar import A_AK, A_BR, K, LOG_TAUTAN

KASUS = [
    # ------------------------------------------------------------------------------------------------ Akun dan masuk
    K("TC-AK-01", A_AK, "Murid", "P1", "Mendaftar lewat tautan undangan yang sah, sampai masuk ke Beranda",
      "Admin sudah membuat undangan untuk email uji yang belum pernah terdaftar. " + LOG_TAUTAN,
      ["Buka tautan undangan di browser.",
       "Periksa layar: judul \"Selamat datang\" (ditambah nama lembaga bila ada), kolom Email sudah terisi.",
       "Isi Nama lengkap, Password (contoh Murid2026) dan Konfirmasi password yang sama.",
       "Tekan Buat Akun.",
       "Selesaikan 3 layar sambutan sampai Mulai Belajar.",
       "Di aplikasi admin, buka Undangan lalu Murid."],
      "Akun terbentuk dan murid langsung masuk (tidak diminta login lagi), terbuka layar sambutan \"Langkah 1 dari 3\". Setelah Mulai Belajar terbuka Beranda "
      "dengan nama dan kelas sesuai undangan. Di admin undangan berstatus Diterima dan murid muncul di daftar Murid, berstatus Aktif, XP 0.",
      "AK-01, AK-03, AK-09, UD-02"),
    K("TC-AK-02", A_AK, "Murid", "P1", "Aturan password dan isian wajib di formulir pendaftaran",
      "Tautan undangan yang sah (belum dipakai).",
      ["Kosongkan Nama lengkap lalu tekan Buat Akun.",
       "Isi nama, password \"abc123\" (7 karakter) dan konfirmasi sama; tekan Buat Akun.",
       "Ganti password jadi \"abcdefgh\" (tanpa angka); tekan Buat Akun.",
       "Ganti password jadi \"12345678\" (tanpa huruf); tekan Buat Akun.",
       "Isi password \"Murid2026\" tetapi konfirmasi \"Murid2027\"; tekan Buat Akun."],
      "Tiap kesalahan memunculkan pesan merah yang jelas: \"Nama lengkap wajib diisi.\", \"Password minimal 8 karakter.\", \"Password harus mengandung huruf dan angka.\" "
      "(dua kali), dan \"Konfirmasi password tidak sama.\". Petunjuk \"Minimal 8 karakter, mengandung huruf dan angka.\" terlihat di dekat kolom. Tidak ada akun yang terbentuk.",
      "AK-01"),
    K("TC-AK-03", A_AK, "Murid", "P2", "Email di formulir pendaftaran terkunci sesuai undangan",
      "Tautan undangan yang sah.",
      ["Buka tautan undangan.", "Coba klik dan mengetik di kolom Email."],
      "Kolom Email sudah berisi email yang diundang, tidak bisa diubah, dan ada keterangan \"Email terkunci sesuai undangan.\".",
      "AK-01"),
    K("TC-AK-04", A_AK, "Murid", "P2", "Tautan undangan yang tidak dikenal",
      "Tidak perlu masuk.",
      ["Buka /invite/token-ngawur di aplikasi murid."],
      "Judul \"Tautan undangan tidak valid\" dan penjelasan \"Tautan ini tidak dikenali...\". Tidak ada formulir pendaftaran.",
      "AK-02"),
    K("TC-AK-05", A_AK, "Murid", "P2", "Undangan kedaluwarsa: pesan jelas dan permintaan undangan ulang dibatasi",
      "Satu undangan yang tautannya sudah disalin. Agar kedaluwarsa tanpa menunggu 7 hari, ubah masa berlakunya di database: "
      "UPDATE invitations SET expires_at = now() - interval '1 day' WHERE email = '<email uji>';",
      ["Buka tautan undangan yang kedaluwarsa.",
       "Tekan Minta undangan ulang.",
       "Ulangi permintaan sampai 4 kali dalam satu jam."],
      "Judul \"Undangan sudah kedaluwarsa\" dan tombol Minta undangan ulang. Permintaan pertama sampai ketiga berhasil (pesan konfirmasi). Permintaan keempat dalam jam yang sama ditolak "
      "dengan pesan \"Terlalu banyak percobaan. Coba lagi beberapa saat lagi.\". Tidak ada formulir pendaftaran.",
      "AK-02", "Butuh akses database untuk menyiapkan data. Batas 3 per jam dihitung per alamat IP, bukan per tautan: penguji di jaringan kantor yang sama berbagi batas ini. "
      "Email ke admin belum terkirim otomatis (AK-10), jadi hasilnya hanya terlihat di log API."),
    K("TC-AK-06", A_AK, "Murid", "P2", "Undangan yang dicabut dan undangan yang sudah dipakai",
      "Satu undangan yang dicabut admin (status Dicabut) dan satu undangan yang sudah dipakai mendaftar (status Diterima); tautan keduanya sudah disalin.",
      ["Buka tautan undangan yang dicabut.", "Buka tautan undangan yang sudah dipakai."],
      "Yang dicabut: \"Undangan sudah dicabut\" dengan anjuran hubungi admin. Yang sudah dipakai: \"Undangan sudah dipakai\" dengan anjuran masuk memakai email dan password yang dibuat. Tidak ada formulir pendaftaran di keduanya.",
      "AK-02"),
    K("TC-AK-07", A_AK, "Murid", "P2", "Layar sambutan tiga langkah",
      "Sudah masuk. Buka /welcome (muncul otomatis setelah mendaftar).",
      ["Pada langkah 1, lihat tiga pilihan target XP (Santai 10, Reguler 30, Serius 50), pilih salah satu, tekan Lanjut.",
       "Pada langkah 2 lihat level tempat belajar dimulai; tekan Lanjut.",
       "Pada langkah 3 periksa ringkasan Kelas, Target harian, Level awal; tekan Kembali dua kali lalu Lanjut dua kali.",
       "Tekan Mulai Belajar."],
      "Penunjuk \"Langkah N dari 3\" selalu benar, pilihan target tersimpan (cek di Profil), Kembali tidak menghilangkan pilihan, dan Mulai Belajar membuka Beranda.",
      "AK-03"),
    K("TC-AK-08", A_AK, "Murid", "P1", "Masuk dengan email dan password yang benar",
      "Akun murid uji aktif.",
      ["Buka aplikasi murid, halaman Masuk.", "Isi Email dan Password.", "Tekan Masuk."],
      "Terbuka Beranda dengan sapaan \"Selamat datang, <nama>\" dan tombol Keluar di menu. Tidak ada pesan galat.",
      "AK-04"),
    K("TC-AK-09", A_AK, "Murid", "P1", "Password salah ditolak dengan pesan yang jelas",
      "Akun murid uji aktif (bukan akun khusus penguncian).",
      ["Isi email yang benar dan password yang salah.", "Tekan Masuk."],
      "Muncul \"Email atau password salah.\" dan murid tetap di halaman Masuk.",
      "AK-04"),
    K("TC-AK-10", A_AK, "Murid", "P1", "Email yang tidak terdaftar mendapat pesan yang sama",
      "Tidak perlu akun.",
      ["Isi email acak yang belum terdaftar dan password sembarang.", "Tekan Masuk."],
      "Pesan persis sama dengan password salah (\"Email atau password salah.\"): aplikasi tidak membocorkan siapa yang terdaftar.",
      "AK-04"),
    K("TC-AK-11", A_AK, "Murid", "P2", "Isian kosong atau email berformat salah tidak dikirim ke server",
      "Tidak perlu akun.",
      ["Tekan Masuk dengan semua kolom kosong.", "Isi email \"bukan-email\" dan password \"x\", tekan Masuk."],
      "Browser menahan formulir dengan petunjuk bawaannya; tidak ada permintaan login ke server (periksa tab Network) dan tidak ada pesan galat server.",
      "AK-04"),
    K("TC-AK-12", A_AK, "Murid", "P1", "Sesi bertahan setelah halaman dimuat ulang dan setelah pindah halaman",
      "Sudah masuk.",
      ["Tekan F5 di Beranda.", "Buka Profil lewat menu, lalu kembali ke Beranda."],
      "Murid tetap masuk (tidak diminta login) dan Beranda tampil lengkap setelah dimuat ulang.",
      "AK-04"),
    K("TC-AK-13", A_AK, "Murid", "P1", "Halaman belajar tidak bisa dibuka tanpa masuk",
      "Belum masuk (keluar dulu atau pakai jendela penyamaran).",
      ["Buka satu per satu: /, /profile, /learn/l1, /conversation, /conversation/ngobrol-ai, /dictionary, /flashcards, /leaderboard, /welcome."],
      "Setiap alamat langsung mengarah ke layar Masuk. Tidak ada isi halaman belajar yang sempat terlihat.",
      "AK-04"),
    K("TC-AK-14", A_AK, "Murid", "P1", "Akun admin tidak bisa masuk di aplikasi murid",
      "Punya akun admin.",
      ["Di halaman Masuk aplikasi murid, isi email dan password admin.", "Tekan Masuk."],
      "\"Email atau password salah.\" Akun admin dan akun murid adalah dua daftar yang terpisah.",
      "AK-04, AD-01"),
    K("TC-AK-15", A_AK, "Murid", "P1", "Akun terkunci 15 menit setelah 5 kali salah password",
      "Pakai akun KHUSUS uji penguncian (QA_LOCKOUT_*). Setelah uji ini akun terkunci 15 menit, jangan pakai akun lain.",
      ["Masukkan password salah berulang sampai pesan berubah.",
       "Setelah terkunci, masukkan password yang BENAR.",
       "Tunggu 15 menit lalu masuk dengan password benar (opsional)."],
      "Setelah kesalahan ke-5 muncul \"Terlalu banyak percobaan gagal. Coba lagi dalam 15 menit.\" Password yang benar pun ditolak dengan pesan yang sama selama terkunci. Setelah 15 menit akun bisa masuk lagi.",
      "AK-05", "Otomatis menguji sampai langkah 2. Langkah 3 hanya bisa dicek manual (menunggu)."),
    K("TC-AK-16", A_AK, "Murid", "P1", "Lupa password: jawaban sama untuk email terdaftar maupun tidak",
      "Tidak perlu masuk.",
      ["Di Masuk tekan Lupa password?.", "Isi email yang tidak terdaftar, tekan Kirim Tautan Reset.", "Ulangi dengan email murid uji yang terdaftar."],
      "Dua-duanya menampilkan layar \"Cek Emailmu\" dengan kalimat yang sama (\"Kalau ... terdaftar, kami sudah mengirim tautan...\" dan masa berlaku 1 jam). Aplikasi tidak membocorkan siapa yang terdaftar.",
      "AK-06", "Catatan: kalimat \"kami sudah mengirim tautan\" tampil walau email belum benar-benar terkirim (AK-10). Pastikan email aktif sebelum rilis."),
    K("TC-AK-17", A_AK, "Murid", "P2", "Batas 3 permintaan reset password per jam untuk satu email",
      "Akses ke log API (docker compose logs api).",
      ["Minta tautan reset untuk email murid uji 4 kali berturut-turut.",
       "Setiap kali, catat tampilan layar dan baris \"[STUB]\" di log API."],
      "Layar selalu sama (\"Cek Emailmu\"), tetapi di log hanya tiga tautan yang tercatat; permintaan keempat dalam satu jam tidak membuat tautan baru.",
      "AK-06", "Batas ini sengaja tidak terlihat di layar (anti pembocoran akun), jadi hanya bisa dibuktikan lewat log."),
    K("TC-AK-18", A_AK, "Murid", "P1", "Membuat password baru lewat tautan reset sampai bisa masuk",
      "Tautan reset yang sah. " + LOG_TAUTAN,
      ["Buka tautan reset.", "Isi Password baru dan Konfirmasi password baru (memenuhi aturan), tekan Simpan Password.",
       "Di layar Masuk, perhatikan pesan, lalu masuk dengan password baru.", "Coba masuk dengan password lama."],
      "Muncul \"Password berhasil diubah. Silakan masuk dengan password barumu.\" Password baru berhasil masuk; password lama ditolak.",
      "AK-07"),
    K("TC-AK-19", A_AK, "Murid", "P2", "Tautan reset yang tidak berlaku",
      "Tidak perlu masuk.",
      ["Buka /reset-password/token-ngawur.", "Isi password baru dan konfirmasi, kirim formulir."],
      "Judul \"Tautan Reset Tidak Berlaku\", penjelasan bahwa tautan berlaku 1 jam dan satu kali pakai, serta tautan Minta Tautan Reset Baru.",
      "AK-07"),
    K("TC-AK-20", A_AK, "Murid", "P2", "Tautan reset hanya bisa dipakai sekali dan kedaluwarsa setelah 1 jam",
      "Tautan reset yang sah dan sudah dipakai satu kali.",
      ["Buka lagi tautan yang sama dan coba ganti password.",
       "(Opsional) Pakai tautan baru yang dibuat lebih dari 1 jam lalu (atau ubah expires_at di database)."],
      "Tautan yang sudah dipakai maupun yang kedaluwarsa menampilkan \"Tautan Reset Tidak Berlaku\"; password tidak berubah.",
      "AK-07"),
    K("TC-AK-21", A_AK, "Murid", "P1", "Keluar mengakhiri sesi di perangkat itu",
      "Sudah masuk.",
      ["Tekan Keluar di menu.", "Tekan tombol kembali browser, lalu buka /learn/l1 secara langsung."],
      "Murid kembali ke layar Masuk. Halaman belajar tidak bisa dibuka lagi tanpa masuk, dan token masuk hilang dari penyimpanan browser.",
      "AK-08"),
    K("TC-AK-22", A_AK, "Murid", "P2", "Sesi bertahan setelah browser ditutup dan dibuka lagi",
      "Sudah masuk di browser biasa (bukan jendela penyamaran).",
      ["Tutup seluruh jendela browser.", "Buka lagi dan langsung ke alamat aplikasi murid."],
      "Murid masih masuk dan Beranda terbuka tanpa mengetik password (sesi berlaku sampai 14 hari tidak dipakai).",
      "AK-04"),
    K("TC-AK-23", A_AK, "Semua", "P1", "Murid yang dinonaktifkan admin: tidak bisa masuk, dan sesi yang sedang berjalan",
      "Murid uji kedua (QA_STUDENT2) dan akun admin.",
      ["Murid masuk di browser A dan biarkan terbuka.",
       "Admin menonaktifkan murid itu (Murid, detail, Nonaktifkan Murid).",
       "Murid mencoba masuk di browser B dengan password yang benar.",
       "Di browser A, muat ulang halaman.",
       "Admin mengaktifkan kembali; murid masuk lagi di browser B."],
      "Langkah 3: \"Email atau password salah.\" (login baru diblokir). Langkah 5: murid bisa masuk lagi. Langkah 4 (yang diharapkan PRD: \"murid tidak bisa login\"): sebaiknya sesi A juga berhenti; "
      "perilaku saat ini sesi A tetap berjalan sampai token pembaruan habis (14 hari).",
      "MR-04, AK-04", "Temuan diketahui di langkah 4; diuji otomatis di TC-AD-26 dan TC-AD-27 (yang kedua ditandai diharapkan gagal). Perlu keputusan pemilik produk."),
    K("TC-AK-24", A_AK, "API", "P2", "Keluar hanya menghapus token di perangkat: token pembaruan lama masih berlaku",
      "Akses terminal dengan curl. Murid uji masuk di browser dan Anda bisa membaca refresh token di Application > Local Storage.",
      ["Salin nilai refresh token dari penyimpanan browser.", "Tekan Keluar di aplikasi.",
       "Kirim POST /auth/refresh dengan token yang disalin: curl -X POST <API>/auth/refresh -H 'content-type: application/json' -d '{\"refreshToken\":\"<token>\"}'."],
      "Yang diharapkan secara keamanan: 401 (sesi sudah dicabut di server). Perilaku saat ini: 200 dan token baru diberikan, karena Keluar belum memanggil server.",
      "AK-08", "Temuan diketahui (tidak ada endpoint logout di API). Catat sebagai keputusan produk, bukan bug baru."),
    K("TC-AK-25", A_AK, "Murid", "P2", "Mengganti password lewat reset memaksa masuk ulang di perangkat lain",
      "Murid uji masuk di dua browser (A dan B).",
      ["Di browser B minta tautan reset, ganti password.", "Di browser A biarkan terbuka, tunggu sampai masa token akses habis (maks 1 jam) atau hapus access token dari penyimpanan lalu muat ulang."],
      "Di browser A sesi tidak bisa diperbarui lagi dan murid diarahkan ke layar Masuk. Password lama tidak berlaku.",
      "AK-07"),
    K("TC-AK-26", A_AK, "Murid", "P2", "Reset password membuka kunci akun yang terkunci",
      "Akun uji penguncian sudah terkunci (5 kali salah).",
      ["Minta tautan reset untuk akun itu dan ganti password.", "Masuk dengan password baru (sebelum 15 menit lewat)."],
      "Murid bisa masuk dengan password baru walau belum 15 menit.",
      "AK-05, AK-07"),
    K("TC-AK-27", A_AK, "Murid", "P3", "Gangguan jaringan saat masuk",
      "DevTools > Network > Offline (atau matikan Wi-Fi).",
      ["Isi email dan password yang benar.", "Tekan Masuk.", "Nyalakan jaringan lagi dan tekan Masuk."],
      "Muncul \"Tidak dapat menghubungi server. Periksa koneksi internetmu lalu coba lagi.\", tombol tidak macet di \"Memproses...\", dan setelah jaringan kembali masuk berhasil.",
      "AK-04"),
    K("TC-AK-28", A_AK, "Murid", "P3", "Email tidak peka huruf besar-kecil dan spasi di ujung diabaikan",
      "Akun murid uji.",
      ["Masuk dengan email ditulis huruf besar semua (mis. QA-MURID@EXAMPLE.COM) dan ada spasi di akhir."],
      "Masuk berhasil. Penghitung percobaan gagal juga tidak terpecah per ejaan.",
      "AK-04"),
    K("TC-AK-29", A_AK, "Murid", "P3", "Pengelola password browser",
      "Browser dengan pengelola password aktif (Chrome, Safari, Firefox).",
      ["Masuk dan setujui tawaran menyimpan password.", "Keluar lalu buka halaman Masuk lagi."],
      "Browser menawarkan menyimpan dan mengisi email serta password; kolom dikenali sebagai email dan password.",
      "AK-04"),
    K("TC-AK-30", A_AK, "Murid", "P3", "Dua tab: keluar di satu tab, tab lain tidak macet",
      "Sudah masuk di dua tab.",
      ["Di tab 2 tekan Keluar.", "Di tab 1 buka halaman lain (mis. Kamus) dan lakukan satu pencarian."],
      "Tab 1 tidak berhenti dengan layar kosong. Murid diarahkan ke Masuk atau diberi pesan yang jelas, tanpa teks galat teknis.",
      "AK-08"),

    # ------------------------------------------------------------------------------------- Beranda dan jalur belajar
    K("TC-BR-01", A_BR, "Murid", "P1", "Beranda menyapa murid dan menampilkan statistik belajar",
      "Sudah masuk.",
      ["Buka Beranda."],
      "Sapaan \"Selamat datang, <nama>\", kartu Streak (hari), Terpanjang (hari), dan \"Pelajaran selesai N/M\" dengan bilah kemajuan; tidak ada teks mentah seperti undefined atau NaN.",
      "BR-01"),
    K("TC-BR-02", A_BR, "Murid", "P1", "Jalur belajar memuat unit dan pelajaran dengan keterangan status",
      "Sudah masuk.",
      ["Gulir seluruh Beranda."],
      "Ada judul level (Hiragana, N4), spanduk tiap unit, dan bulatan pelajaran. Tiap pelajaran bisa dibaca statusnya oleh pembaca layar: terkunci, tersedia, atau selesai (beserta bintang).",
      "BR-03"),
    K("TC-BR-03", A_BR, "Murid", "P1", "Tombol Lanjutkan Belajar membuka pelajaran berikutnya",
      "Ada pelajaran yang belum selesai.",
      ["Tekan Lanjutkan Belajar di kartu sambutan."],
      "Terbuka pelajaran pertama yang masih tersedia (murid baru: Baris a, ka, sa) dengan tombol Tutup pelajaran di pojok.",
      "BR-02"),
    K("TC-BR-04", A_BR, "Murid", "P1", "Pelajaran terkunci tidak bisa diklik",
      "Murid baru (hanya pelajaran pertama terbuka).",
      ["Klik pelajaran berikon gembok.", "Arahkan kursor ke pelajaran terkunci."],
      "Tidak terjadi apa-apa (tetap di Beranda), kursor menunjukkan tidak boleh, dan tooltip \"Terkunci\".",
      "BR-04"),
    K("TC-BR-05", A_BR, "Murid", "P2", "Pelajaran terkunci dibuka lewat alamat langsung: hasilnya ditolak server",
      "Murid baru; pelajaran Youon 2, sokuon, dan vokal panjang (l7) masih terkunci.",
      ["Buka /learn/l7 langsung di browser.", "Kerjakan pelajaran sampai soal terakhir.", "Kembali ke Beranda."],
      "Isi pelajaran tetap tampil (hanya pengiriman hasil yang dijaga server), tetapi di akhir muncul \"Gagal mengirim hasil belajar.\" dan tombol Kembali ke Beranda. "
      "Pelajaran tetap terkunci, jumlah \"Pelajaran selesai\" tidak berubah, tidak ada XP.",
      "BR-04", "Perilaku yang dirancang: server menjadi penegak kunci. Catat bila tim ingin layar pelajaran juga menolak dibuka."),
    K("TC-BR-06", A_BR, "Murid", "P2", "Alamat pelajaran yang tidak ada",
      "Sudah masuk.",
      ["Buka /learn/tidak-ada."],
      "Pesan \"Gagal memuat pelajaran.\" dan tombol Kembali ke Beranda; bukan layar kosong.",
      "BR-03"),
    K("TC-BR-07", A_BR, "Murid", "P1", "Menu utama membuka semua halaman",
      "Sudah masuk.",
      ["Klik tiap menu: Percakapan, Kamus, Flashcard, Leaderboard, Profil, Beranda."],
      "Setiap menu membuka halamannya, menu aktif ditandai, dan judul halaman benar.",
      "TP-02"),
    K("TC-BR-08", A_BR, "Murid", "P2", "Unit di level lanjutan (N4) terkunci untuk murid baru",
      "Murid baru.",
      ["Gulir ke bawah di Beranda sampai unit \"Percakapan di Tempat Kerja\"."],
      "Spanduk unit kelabu dengan gembok dan hitungan 0/11; pelajarannya terkunci.",
      "MT-02, BR-04"),
    K("TC-BR-09", A_BR, "Murid", "P2", "Pelajaran yang sudah selesai menampilkan bintang sesuai hasil",
      "Sudah menyelesaikan satu pelajaran.",
      ["Lihat bulatan pelajaran itu di peta.", "Klik untuk membukanya lagi."],
      "Bulatan emas dengan 1 sampai 3 bintang menyala sesuai skor terbaik, dan pelajaran masih bisa dibuka untuk diulang.",
      "BR-03, NL-02"),
    K("TC-BR-10", A_BR, "Murid", "P3", "Gelembung MULAI hanya di pelajaran yang sedang dikerjakan",
      "Murid yang sudah menyelesaikan sebagian pelajaran.",
      ["Lihat peta pelajaran."],
      "Gelembung \"MULAI\" berdenyut hanya di pelajaran yang jadi tujuan Lanjutkan Belajar; pelajaran lain tidak punya.",
      "BR-02"),
    K("TC-BR-11", A_BR, "Murid", "P3", "Judul pelajaran berpola Jepang tidak terpotong di tengah",
      "Layar sempit (lebar ponsel) dan lebar.",
      ["Lihat unit \"Percakapan di Tempat Kerja\", mis. \"Keadaan Sedang Berlangsung (～ている)\"."],
      "Nama pelajaran dan pola Jepangnya dalam kurung tampil di baris terpisah; pola tidak terputus di tengah huruf (mis. \"～てい / る\").",
      "BR-03, TP-04"),
    K("TC-BR-12", A_BR, "Murid", "P3", "Hitungan pelajaran selesai konsisten di semua tempat",
      "Murid dengan beberapa pelajaran selesai.",
      ["Bandingkan \"Pelajaran selesai N/M\" di kartu sambutan dengan jumlah hitungan di spanduk tiap unit."],
      "Jumlah selesai di kartu sambutan sama dengan penjumlahan hitungan semua unit, dan M sama dengan total pelajaran.",
      "BR-01"),
    K("TC-BR-13", A_BR, "Murid", "P2", "Pelajaran berikutnya terbuka berurutan dan unit N4 terbuka setelah Hiragana tamat",
      "Murid baru, waktu cukup (7 pelajaran Hiragana).",
      ["Lulus pelajaran 1.", "Periksa bahwa pelajaran 2 terbuka dan pelajaran 3 masih terkunci.", "Lulus sampai pelajaran 7.", "Lihat unit \"Percakapan di Tempat Kerja\"."],
      "Setiap kelulusan membuka satu pelajaran berikutnya. Setelah pelajaran 7 lulus, unit N4 terbuka dan pelajaran pertamanya tersedia.",
      "BR-04, MT-02", "Memakan waktu; cocok dijalankan sekali per rilis dengan akun baru."),
    K("TC-BR-14", A_BR, "Murid", "P3", "Semua pelajaran selesai",
      "Akun yang sudah menamatkan seluruh pelajaran (bisa disiapkan bertahap).",
      ["Buka Beranda."],
      "Tombol Lanjutkan Belajar hilang dan muncul kalimat \"Hebat! Semua pelajaran sudah selesai\".",
      "BR-02", "Opsional: butuh akun yang menamatkan 18 pelajaran."),
]
