"""Kasus uji: Tampilan ponsel dan layar (RS), Aksesibilitas (AX)."""
from kasus_dasar import A_AX, A_RS, K

KASUS = [
    # ----------------------------------------------------------------------------------- Tampilan ponsel dan layar
    K("TC-RS-01", A_RS, "Murid", "P1", "Beranda memakai tab bawah (bukan sidebar), tanpa gulir ke samping",
      "Ponsel atau emulasi 412 px.",
      ["Buka Beranda di ponsel."],
      "Bilah atas (merek, avatar Profil, Keluar) dan tab bawah dengan lima menu (Beranda, Percakapan, Kamus, Flashcard, Leaderboard). Tidak ada sidebar, tidak ada gulir ke samping.",
      "TP-02"),
    K("TC-RS-02", A_RS, "Murid", "P1", "Tab bawah, avatar, dan Keluar mudah disentuh",
      "Ponsel.",
      ["Sentuh tiap tab dan avatar Profil.", "Perhatikan ukuran area sentuh."],
      "Setiap tab membuka halamannya; area sentuh minimal sekitar 44 px; Profil dibuka lewat avatar.",
      "TP-02, TP-04"),
    K("TC-RS-03", A_RS, "Murid", "P1", "Layar pelajaran di ponsel: soal dan pilihan utuh dan mudah disentuh",
      "Ponsel.",
      ["Buka satu pelajaran.", "Jawab beberapa soal pilih dan satu soal susun."],
      "Soal, empat pilihan/kepingan, dan tombol terlihat utuh; tab bawah tidak menutupi pilihan; tidak ada gulir ke samping.",
      "TP-02, PL-03, PL-04"),
    K("TC-RS-04", A_RS, "Murid", "P2", "Kamus di ponsel: satu kolom dan tanpa gulir ke samping",
      "Ponsel.",
      ["Cari huruf \"a\"."],
      "Kartu hasil tersusun satu kolom, teks terbaca, tidak melebar.",
      "KM-02, TP-02"),
    K("TC-RS-05", A_RS, "Murid", "P1", "Ngobrol dengan AI di ponsel: kotak kirim tidak tertutup tab bawah",
      "Ponsel.",
      ["Buka Ngobrol dengan AI, Mulai Ngobrol.", "Ketuk kolom ketik sehingga keyboard layar muncul."],
      "Tombol mikrofon dan kirim terlihat di atas tab bawah dan cukup besar (minimal 44 px); saat keyboard muncul kolom ketik tidak tertutup; tidak ada gulir ke samping.",
      "AI-06, TP-02"),
    K("TC-RS-06", A_RS, "Murid", "P2", "Profil di ponsel: formulir bisa diisi dan tombol Simpan terjangkau",
      "Ponsel.",
      ["Buka Profil.", "Gulir ke bawah sampai tombol Simpan Perubahan."],
      "Formulir terisi normal; tombol Simpan tidak tertutup tab bawah setelah digulir.",
      "GM-04, TP-02"),
    K("TC-RS-07", A_RS, "Murid", "P2", "Leaderboard, Flashcard, dan Percakapan di ponsel tidak melebar",
      "Ponsel.",
      ["Buka masing-masing halaman."],
      "Tidak ada gulir ke samping dan tidak ada teks terpotong.",
      "TP-02"),
    K("TC-RS-08", A_RS, "Murid", "P1", "Ponsel Android sungguhan: alur inti dari masuk sampai hasil pelajaran",
      "Ponsel Android (Chrome) sungguhan, jaringan seluler atau Wi-Fi.",
      ["Masuk.", "Kerjakan satu pelajaran sampai hasil.", "Buka Kamus, cari satu kata.", "Buka Leaderboard dan Profil.", "Keluar."],
      "Semua langkah berjalan tanpa galat, sentuhan terasa responsif, teks terbaca tanpa perlu memperbesar.",
      "TP-02", "Catat model ponsel dan versi Android/Chrome di lembar Perangkat."),
    K("TC-RS-09", A_RS, "Murid", "P1", "iPhone Safari sungguhan: alur inti dan area aman",
      "iPhone (Safari) sungguhan.",
      ["Masuk dan kerjakan satu pelajaran.", "Buka Ngobrol dengan AI dan ketuk kolom ketik.", "Gulir halaman panjang sampai bilah alamat Safari menyusut."],
      "Tab bawah tidak tertutup bilah home; layar tidak melompat atau memperbesar sendiri saat mengetik; semua fungsi berjalan. Rekam suara berfungsi bila alamat HTTPS.",
      "TP-02, TP-06", "Safari tidak dicakup skrip otomatis (hanya Chromium); uji manual wajib."),
    K("TC-RS-10", A_RS, "Murid", "P2", "Memutar layar (potret dan lanskap) di tengah pelajaran dan chat",
      "Ponsel atau tablet.",
      ["Mulai pelajaran, jawab satu soal, putar layar ke lanskap lalu kembali.", "Ulangi di layar Ngobrol dengan AI."],
      "Tata letak menyesuaikan, kemajuan dan isi percakapan tidak hilang, tidak ada elemen terpotong.",
      "TP-02"),
    K("TC-RS-11", A_RS, "Murid", "P2", "Layar sangat sempit (320 px)",
      "Emulasi 320 px (iPhone SE lama) atau ponsel kecil.",
      ["Buka Beranda, pelajaran, Percakapan, Profil."],
      "Tidak ada elemen terpotong atau bertumpuk; di bawah 360 px tombol Keluar hanya berupa ikon tetapi tetap bisa disentuh dan terbaca pembaca layar.",
      "TP-02"),
    K("TC-RS-12", A_RS, "Murid", "P3", "Tablet (768 px dan 1024 px)",
      "Emulasi iPad atau tablet sungguhan.",
      ["Buka Beranda dan pelajaran pada 768 px dan 1024 px."],
      "Pada 768 px ke atas muncul sidebar berwarna; di bawahnya tab bawah. Tidak ada tumpang tindih saat berpindah ukuran.",
      "TP-02"),
    K("TC-RS-13", A_RS, "Murid", "P3", "Layar lebar (1920 px) dan zoom browser 200%",
      "Desktop.",
      ["Buka Beranda di 1920 px.", "Zoom browser ke 200% dan buka Beranda, pelajaran, dan Profil."],
      "Isi terpusat dengan lebar maksimal wajar; pada zoom 200% tidak ada konten hilang atau tertutup (tata letak beralih ke versi ponsel).",
      "TP-02, TP-04"),
    K("TC-RS-14", A_RS, "Murid", "P3", "Koneksi lambat: ada penanda memuat, bukan layar putih",
      "DevTools > Network > Slow 3G.",
      ["Muat ulang Beranda, Kamus, dan pelajaran."],
      "Selama memuat tampil \"Memuat...\" (kelopak sakura memantul); halaman akhirnya terisi lengkap; tidak ada tombol yang bisa ditekan sebelum datanya siap.",
      "TP-04"),
    K("TC-RS-15", A_RS, "Murid", "P3", "Tema warna Biru Samudra konsisten",
      "Sudah masuk.",
      ["Buka semua halaman murid dan layar masuk/daftar/lupa password."],
      "Warna dasar biru-teal-hijau konsisten; tidak ada sisa warna ungu dari tema lama atau komponen berwarna janggal.",
      "TP-01"),
    K("TC-RS-16", A_RS, "Murid", "P3", "Animasi dan perayaan menghormati pengaturan \"Kurangi gerakan\"",
      "Aktifkan \"Kurangi gerakan\" (reduce motion) di sistem operasi.",
      ["Selesaikan satu pelajaran dengan lulus.", "Perhatikan hiasan melayang dan konfeti."],
      "Tanpa pengaturan itu ada perayaan dan hiasan bergerak; dengan pengaturan itu konfeti tidak tampil dan hiasan tidak bergerak, dan layar tetap berfungsi penuh.",
      "TP-03"),
    K("TC-RS-17", A_RS, "Murid", "P3", "Mode gelap sistem tidak merusak tampilan",
      "Aktifkan mode gelap di sistem atau browser.",
      ["Buka beberapa halaman murid."],
      "Tampilan tetap terbaca (aplikasi memakai satu tema terang); tidak ada teks gelap di latar gelap.",
      "TP-01"),
    K("TC-RS-18", A_RS, "Murid", "P3", "Aplikasi hanya bisa dipakai saat tersambung internet",
      "Sudah masuk; DevTools > Network > Offline.",
      ["Muat ulang halaman.", "Coba berpindah halaman di dalam aplikasi."],
      "Tanpa internet halaman tidak bisa dimuat dan data tidak tampil (materi tidak disimpan untuk offline). Pastikan tidak ada klaim \"bisa dipakai tanpa internet\".",
      "TP-06", "Sesuai dokumen fitur: ikon pemasangan ke layar utama juga belum dibuat."),

    # ------------------------------------------------------------------------------------------------ Aksesibilitas
    K("TC-AX-01", A_AX, "Murid", "P1", "Pemindaian otomatis (axe): halaman murid yang butuh masuk",
      "Skrip otomatis; tidak ada langkah manual.",
      ["Jalankan npm run test:a11y."],
      "Tidak ada pelanggaran WCAG 2.1 A/AA tingkat serius atau kritis pada Beranda, Percakapan, pengantar skenario, Ngobrol dengan AI, Kamus, Flashcard, Leaderboard, Profil, sambutan, dan layar pelajaran.",
      "TP-04", "Pemindaian otomatis hanya menangkap sebagian masalah; lanjutkan dengan TC-AX-04 sampai TC-AX-09."),
    K("TC-AX-02", A_AX, "Murid", "P1", "Pemindaian otomatis (axe): halaman murid tanpa masuk",
      "Skrip otomatis.",
      ["Jalankan npm run test:a11y."],
      "Tidak ada pelanggaran serius/kritis pada Masuk, Lupa password, Reset password, dan Undangan.",
      "TP-04"),
    K("TC-AX-03", A_AX, "Admin", "P2", "Pemindaian otomatis (axe): aplikasi admin",
      "Skrip otomatis.",
      ["Jalankan npm run test:a11y."],
      "Tidak ada pelanggaran serius/kritis baru pada Dashboard, Undangan, Kelas, Murid, dan Pengaturan.",
      "AD-03", "Temuan diketahui: label peran admin di menu (abu-abu muda) kurang kontras dan judul kolom tabel tanpa scope. Dicatat sebagai temuan, tidak menggagalkan skrip."),
    K("TC-AX-04", A_AX, "Murid", "P1", "Hanya dengan keyboard: masuk, kerjakan pelajaran, lihat hasil",
      "Komputer; jangan pakai mouse.",
      ["Pakai Tab, Shift+Tab, Enter, dan Spasi untuk masuk.", "Buka pelajaran, jawab soal pilih dan soal susun, tekan Lanjut, sampai hasil.", "Buka menu Kamus dan cari satu kata."],
      "Semua kontrol bisa dicapai dan dioperasikan; fokus selalu terlihat jelas (cincin biru) dan urutannya masuk akal; tidak ada jebakan fokus; pilihan yang terkunci tidak bisa difokus ulang secara membingungkan.",
      "TP-04"),
    K("TC-AX-05", A_AX, "Murid", "P2", "Pembaca layar (NVDA, VoiceOver, atau TalkBack)",
      "Pembaca layar aktif.",
      ["Buka Beranda dan dengarkan status tiap pelajaran.", "Kerjakan satu soal dan dengarkan umpan balik.", "Buka layar hasil."],
      "Judul halaman terbaca; pelajaran diumumkan sebagai terkunci/tersedia/selesai dengan jumlah bintang; \"Benar!\" atau \"Kurang tepat\" diumumkan; bilah kemajuan punya nama; bintang hasil dibaca \"N dari 3 bintang\".",
      "TP-04", "Teks Jepang bertanda bahasa Jepang supaya dibaca dengan suara Jepang."),
    K("TC-AX-06", A_AX, "Murid", "P3", "Kontras teks di atas gradien",
      "Alat pemeriksa kontras (mis. ekstensi axe DevTools atau Colour Contrast Analyser).",
      ["Periksa teks putih di kartu sambutan, spanduk unit, layar hasil, dan tombol."],
      "Rasio kontras minimal 4,5:1 untuk teks biasa (3:1 untuk teks besar).",
      "TP-04"),
    K("TC-AX-07", A_AX, "Murid", "P3", "Teks diperbesar 200% tidak terpotong",
      "Browser dengan ukuran font diperbesar atau zoom teks 200%.",
      ["Buka Beranda, pelajaran, Percakapan, Profil."],
      "Tidak ada teks terpotong atau tertimpa elemen lain; semua tombol tetap terjangkau.",
      "TP-04"),
    K("TC-AX-08", A_AX, "Murid", "P3", "Label formulir dan pesan galat terkait dengan kolomnya",
      "Layar Masuk dan Profil.",
      ["Kirim formulir dengan isian salah dan dengarkan/inspeksi pesan galat."],
      "Setiap kolom punya label yang terbaca; pesan galat muncul di area pemberitahuan (role alert) sehingga diumumkan pembaca layar.",
      "TP-04"),
    K("TC-AX-09", A_AX, "Admin", "P3", "Aplikasi admin dengan keyboard dan pembaca layar",
      "Aplikasi admin.",
      ["Masuk, buka Kelas, buat kelas, arsipkan, hanya dengan keyboard.", "Periksa apakah judul kolom tabel dibaca sebagai judul kolom."],
      "Semua tombol dan tautan terjangkau keyboard. Judul kolom tabel belum bertanda scope sehingga sebagian pembaca layar tidak membacanya sebagai judul (temuan diketahui, tingkat ringan).",
      "AD-03"),
]
