"""Kasus uji: aplikasi Admin (AD)."""
from kasus_dasar import A_AD, K, LOG_TAUTAN

KASUS = [
    K("TC-AD-01", A_AD, "Admin", "P1", "Masuk dengan akun admin yang benar membuka Dashboard",
      "Akun admin aktif.",
      ["Buka aplikasi admin.", "Isi Email dan Password admin, tekan Masuk."],
      "Terbuka Dashboard, menu menampilkan \"Halo, <nama> (<peran>)\" dan tombol Keluar.",
      "AD-01, AD-03"),
    K("TC-AD-02", A_AD, "Admin", "P1", "Password salah ditolak dengan pesan yang jelas",
      "Akun admin aktif (jangan lebih dari 4 kali berturut-turut: 5 kali salah mengunci akun 15 menit).",
      ["Masukkan password yang salah, tekan Masuk."],
      "\"Email atau password salah.\" dan tetap di layar Masuk.",
      "AD-01"),
    K("TC-AD-03", A_AD, "Admin", "P1", "Akun murid tidak bisa masuk di aplikasi admin",
      "Akun murid uji.",
      ["Masukkan email dan password murid di layar Masuk admin."],
      "\"Email atau password salah.\"",
      "AD-01"),
    K("TC-AD-04", A_AD, "Admin", "P2", "Isian kosong atau email berformat salah ditahan di browser",
      "Tidak perlu masuk.",
      ["Tekan Masuk dengan isian kosong.", "Isi email \"bukan-email\" dan password \"x\", tekan Masuk."],
      "Browser menahan formulir; tidak ada permintaan login ke server.",
      "AD-01"),
    K("TC-AD-05", A_AD, "Admin", "P1", "Belum masuk: semua halaman admin mengarah ke layar Masuk",
      "Belum masuk (jendela penyamaran).",
      ["Buka /, /invitations, /classes, /students, /students/xyz, /settings."],
      "Semuanya langsung mengarah ke layar Masuk.",
      "AD-01, AD-03"),
    K("TC-AD-06", A_AD, "Admin", "P1", "Dashboard menampilkan tiga angka ringkasan, distribusi streak, dan penyelesaian per kelas",
      "Sudah masuk sebagai admin.",
      ["Buka Dashboard."],
      "Kartu \"Murid aktif minggu ini\", \"Total murid aktif\", \"Rata-rata XP\" berisi angka; grafik batang \"Distribusi Streak\" dengan kelompok 0, 1-3, 4-7, 8-14, 15-30, 30+; tabel \"Tingkat Penyelesaian Lesson per Kelas\" atau pesan \"Belum ada kelas aktif.\".",
      "DB-01, DB-02, DB-03"),
    K("TC-AD-07", A_AD, "Admin", "P2", "Menu admin membuka semua halamannya dan sesi bertahan setelah muat ulang",
      "Sudah masuk.",
      ["Klik Undangan, Kelas, Murid, Pengaturan, Dashboard.", "Muat ulang di halaman Kelas."],
      "Tiap menu membuka halaman yang benar; setelah dimuat ulang admin tetap masuk di halaman yang sama.",
      "AD-03"),
    K("TC-AD-08", A_AD, "Admin", "P1", "Keluar mengakhiri sesi admin",
      "Sudah masuk.",
      ["Tekan Keluar.", "Buka /students langsung."],
      "Kembali ke layar Masuk dan halaman admin tidak terbuka tanpa masuk lagi.",
      "AD-01"),
    K("TC-AD-09", A_AD, "Admin", "P3", "Halaman Pengaturan belum tersedia dan menyatakannya dengan jelas",
      "Sudah masuk.",
      ["Buka Pengaturan."],
      "Judul \"Pengaturan\" dan keterangan \"Halaman ini belum diimplementasikan.\" (sesuai dokumen fitur PG-01).",
      "PG-01"),
    K("TC-AD-10", A_AD, "Admin", "P1", "Membuat kelas baru",
      "Sudah masuk.",
      ["Buka Kelas, isi Nama Kelas (dan Deskripsi), tekan Buat Kelas."],
      "Kelas muncul di tabel berstatus Aktif dengan jumlah murid 0, tombol Arsipkan, dan formulir kosong kembali.",
      "KL-01, KL-02"),
    K("TC-AD-11", A_AD, "Admin", "P2", "Nama kelas wajib diisi",
      "Sudah masuk.",
      ["Tekan Buat Kelas dengan nama kosong.", "Ulangi dengan nama hanya spasi."],
      "Nama kosong ditahan browser. Nama spasi tidak membuat kelas tanpa nama (ditolak atau dipangkas).",
      "KL-01"),
    K("TC-AD-12", A_AD, "Admin", "P1", "Kelas yang diarsipkan hilang dari pilihan kelas undangan tetapi tetap ada di filter",
      "Ada kelas aktif.",
      ["Arsipkan kelas di halaman Kelas.", "Buka Undangan; periksa pilihan Kelas pada formulir dan Filter Kelas."],
      "Status kelas menjadi Diarsipkan dengan tombol Buka Arsip. Kelas itu tidak ada di pilihan formulir undangan tetapi masih ada di Filter Kelas.",
      "KL-03, UD-01"),
    K("TC-AD-13", A_AD, "Admin", "P2", "Membuka arsip mengembalikan kelas ke status Aktif",
      "Ada kelas diarsipkan.",
      ["Tekan Buka Arsip.", "Cek pilihan kelas di formulir undangan."],
      "Status Aktif lagi dan kelas kembali ada di pilihan undangan.",
      "KL-03"),
    K("TC-AD-14", A_AD, "Admin", "P1", "Membuat undangan: berstatus Menunggu dengan tombol Kirim Ulang dan Cabut",
      "Ada kelas aktif; email uji belum terdaftar.",
      ["Buka Undangan, isi Nama, Email, pilih Kelas, tekan Kirim Undangan.", "Ambil tautan dari log API."],
      "Baris baru berstatus Menunggu dengan tanggal kedaluwarsa (7 hari), tombol Kirim Ulang dan Cabut, dan formulir kosong kembali. Di log API tercatat \"[STUB] Undangan ke <email> ... <tautan>\".",
      "UD-01, UD-02", LOG_TAUTAN),
    K("TC-AD-15", A_AD, "Admin", "P1", "Undangan kedua untuk email yang masih punya undangan aktif ditolak",
      "Ada undangan berstatus Menunggu.",
      ["Kirim undangan lagi untuk email yang sama."],
      "Pesan \"Gagal mengirim undangan -- pastikan email belum terdaftar/punya undangan aktif lain.\"; tidak ada baris ganda.",
      "UD-01"),
    K("TC-AD-16", A_AD, "Admin", "P1", "Undangan untuk email yang sudah terdaftar sebagai murid ditolak",
      "Ada murid terdaftar.",
      ["Kirim undangan untuk email murid itu."],
      "Pesan yang sama seperti di atas; tidak ada undangan baru.",
      "UD-01"),
    K("TC-AD-17", A_AD, "Admin", "P2", "Formulir undangan menahan email salah format dan mewajibkan kelas",
      "Sudah masuk.",
      ["Isi email \"bukan-email\" lalu Kirim Undangan.", "Isi email benar tetapi tidak memilih kelas."],
      "Browser menahan kedua kasus; tidak ada undangan terbentuk.",
      "UD-01"),
    K("TC-AD-18", A_AD, "Admin", "P2", "Kirim Ulang menerbitkan tautan baru dan undangan tetap Menunggu",
      "Ada undangan Menunggu.",
      ["Tekan Kirim Ulang.", "Ambil tautan baru dari log API dan coba tautan lama."],
      "Tidak ada galat; tanggal kedaluwarsa diperbarui 7 hari; tautan baru berfungsi dan tautan lama tidak berlaku (Tautan undangan tidak valid).",
      "UD-03", LOG_TAUTAN),
    K("TC-AD-19", A_AD, "Admin", "P2", "Filter status dan filter kelas menyaring daftar undangan",
      "Ada beberapa undangan dengan status berbeda.",
      ["Pilih Filter Status Menunggu, Diterima, Kedaluwarsa, Dicabut.", "Pilih Filter Kelas."],
      "Daftar hanya memuat baris yang sesuai; \"Semua\" mengembalikan seluruh daftar.",
      "UD-02"),
    K("TC-AD-20", A_AD, "Admin", "P1", "Mencabut undangan meminta konfirmasi dan mengubah status ke Dicabut",
      "Ada undangan Menunggu.",
      ["Tekan Cabut, pilih Batal pada konfirmasi.", "Tekan Cabut lagi dan setujui."],
      "Konfirmasi menyebut email undangan. Batal tidak mengubah apa pun. Setuju mengubah status menjadi Dicabut dan tombol Kirim Ulang/Cabut hilang. Tautan lama menampilkan \"Undangan sudah dicabut\".",
      "UD-04"),
    K("TC-AD-21", A_AD, "Admin", "P2", "Setelah dicabut, email yang sama bisa diundang lagi",
      "Ada undangan Dicabut.",
      ["Kirim undangan baru untuk email yang sama."],
      "Undangan baru berhasil dan berstatus Menunggu.",
      "UD-01, UD-04"),
    K("TC-AD-22", A_AD, "Admin", "P1", "Daftar murid menampilkan nama, email, kelas, status, XP, dan streak serta bisa disaring per kelas",
      "Ada beberapa murid di dua kelas.",
      ["Buka Murid.", "Pilih Filter Kelas."],
      "Tabel dengan kolom Nama, Email, Kelas, Status (Aktif/Nonaktif), XP, Streak, dan tautan Lihat detail. Filter hanya menampilkan murid kelas itu.",
      "MR-01"),
    K("TC-AD-23", A_AD, "Admin", "P1", "Detail murid: profil, empat angka, dan tiga tabel kemajuan",
      "Murid yang sudah mengerjakan beberapa pelajaran dan satu skenario.",
      ["Buka Lihat detail pada satu murid."],
      "Nama, email, kelas, tanggal bergabung/terakhir aktif, status; kartu Level, Total XP, Streak Saat Ini, Streak Terpanjang; tabel Progres per Unit (pelajaran selesai dan rata-rata bintang), Skor Percakapan, dan Aktivitas Terbaru. Angka cocok dengan yang dialami murid.",
      "MR-02, MR-06"),
    K("TC-AD-24", A_AD, "Admin", "P3", "Detail murid yang tidak ada",
      "Sudah masuk.",
      ["Buka /students/id-tidak-ada."],
      "Pesan \"Gagal memuat data murid.\", bukan layar kosong.",
      "MR-02"),
    K("TC-AD-25", A_AD, "Admin", "P1", "Memindahkan murid ke kelas lain",
      "Murid uji kedua dan dua kelas aktif.",
      ["Di detail murid pilih kelas lain di Pindah Kelas, tekan Pindahkan.", "Cek di aplikasi murid (Profil) dan di Leaderboard.", "Pindahkan kembali."],
      "Keterangan kelas di detail berubah; tombol Pindahkan mati bila kelas tujuan sama; di aplikasi murid kelas berubah dan Leaderboard mengikuti kelas baru.",
      "MR-03, AK-09"),
    K("TC-AD-26", A_AD, "Semua", "P1", "Menonaktifkan murid: tidak bisa masuk lagi; mengaktifkan mengembalikan akses",
      "Murid uji kedua.",
      ["Tekan Nonaktifkan Murid.", "Murid mencoba masuk.", "Tekan Aktifkan Murid; murid masuk lagi."],
      "Badge menjadi Nonaktif dan tombol berubah menjadi Aktifkan Murid. Murid nonaktif ditolak (\"Email atau password salah.\"). Setelah diaktifkan murid bisa masuk dan datanya utuh.",
      "MR-04"),
    K("TC-AD-27", A_AD, "Semua", "P1", "Murid yang sedang masuk lalu dinonaktifkan kehilangan akses",
      "Murid uji kedua masuk di browser lain.",
      ["Admin menonaktifkan murid itu.", "Murid memuat ulang halaman."],
      "Yang diharapkan: murid diarahkan ke layar Masuk. Perilaku saat ini: sesinya tetap berjalan sampai token pembaruan habis (14 hari).",
      "MR-04, AK-04", "Temuan diketahui; skrip otomatis menandainya \"diharapkan gagal\" (test.fail) dan akan memberi tahu bila perilakunya sudah berubah. Perlu keputusan pemilik produk."),
    K("TC-AD-28", A_AD, "Admin", "P2", "Tombol Kirim Email Reset Password memberi pesan berhasil atau pesan batas per jam",
      "Murid uji kedua.",
      ["Tekan Kirim Email Reset Password.", "Cek log API; tekan beberapa kali lagi sampai melewati 3 kali per jam."],
      "Pesan hijau \"Email reset password sudah dikirim ke murid.\" dan di log tercatat \"[STUB] Reset password ke ...\". Setelah 3 kali dalam satu jam, admin mendapat pesan batas yang jelas (berbeda dengan layar murid yang sengaja diam).",
      "MR-05", LOG_TAUTAN),
    K("TC-AD-29", A_AD, "Admin", "P2", "Undangan massal lewat CSV: belum ada layarnya, endpoint ada",
      "Akses terminal; token admin.",
      ["Pastikan halaman Undangan tidak punya tombol unggah CSV.", "Unduh templat: GET /admin/invitations/template.", "Kirim CSV berisi baris campuran (valid, email ganda, format salah, kelas tidak ada, email sudah terdaftar) ke POST /admin/invitations/bulk."],
      "Tidak ada tombol unggah di layar (tidak ada janji palsu). Endpoint menjawab laporan terkirim dan gagal per baris dengan alasan yang tepat.",
      "UD-05", "Hanya lewat API (curl atau Postman)."),
    K("TC-AD-30", A_AD, "Admin", "P1", "Alamat di tautan undangan dan reset menunjuk ke aplikasi murid yang benar",
      "Server hasil deploy (bukan localhost).",
      ["Buat satu undangan dan minta satu tautan reset.", "Baca alamat lengkap tautan di log API."],
      "Tautan memakai alamat publik aplikasi murid yang dipakai penguji (https://...), bukan localhost atau alamat internal, dan bisa dibuka dari ponsel di luar jaringan server.",
      "UD-01, AK-06", "Alamat diambil dari pengaturan CORS_ORIGIN_STUDENT di API (di Docker dibentuk dari PUBLIC_STUDENT_URL di .env); kesalahan pengaturan ini sering terlewat saat deploy."),
    K("TC-AD-31", A_AD, "Admin", "P3", "Daftar besar: puluhan kelas dan ratusan murid",
      "Data uji banyak (skrip student:create berulang atau impor).",
      ["Buka Murid, Kelas, dan Undangan dengan data besar.", "Gulir dan saring."],
      "Halaman tetap termuat dalam beberapa detik, tidak membeku, dan tabel tetap terbaca (belum ada penomoran halaman; catat bila daftar jadi terlalu panjang).",
      "MR-01, KL-02"),
    K("TC-AD-32", A_AD, "Admin", "P3", "Aplikasi admin di tablet dan ponsel",
      "Tablet atau emulasi 768 px dan 412 px.",
      ["Buka semua halaman admin."],
      "Tata letak bertumpuk (menu di atas isi), tabel bisa dibaca atau digulir; formulir bisa diisi. Aplikasi admin dirancang untuk komputer sehingga cukup bisa dipakai.",
      "AD-03"),
    K("TC-AD-33", A_AD, "Admin", "P3", "Dua admin bekerja bersamaan",
      "Dua akun admin atau dua browser.",
      ["Admin A dan B membuka halaman Kelas.", "A membuat kelas; B memuat ulang.", "A dan B memindahkan murid yang sama ke kelas berbeda hampir bersamaan."],
      "Data konsisten; tidak ada galat teknis di layar; hasil akhir adalah salah satu dari dua perubahan (yang terakhir menang).",
      "AD-02"),
    K("TC-AD-34", A_AD, "Admin", "P3", "Peran admin belum membedakan hak akses",
      "Dua akun admin dengan peran berbeda (bila ada).",
      ["Masuk dengan tiap akun dan coba semua menu."],
      "Semua admin aktif punya akses yang sama (sesuai dokumen fitur AD-02: peran belum membedakan hak akses; belum ada layar kelola akun admin).",
      "AD-02"),
    K("TC-AD-35", A_AD, "Admin", "P3", "Fitur admin yang belum ada tidak dijanjikan di layar",
      "Sudah masuk.",
      ["Periksa menu dan halaman mencari: ekspor laporan, pengumuman, editor materi, grafik kalender aktivitas, ubah nama kelas."],
      "Tidak ada tombol atau tautan yang membuka halaman setengah jadi, kecuali Pengaturan yang menyatakan belum diimplementasikan.",
      "PG-02, MR-07, KL-04"),
]
